import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';



class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('ar'),
    Locale('en'),
    Locale('fr'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const _values = <String, Map<String, String>>{
    'ar': {
      'einoProviderBusy': 'مزود الذكاء الاصطناعي مشغول حاليًا. انتظر قليلًا ثم أعد المحاولة.',
      'einoProviderUnavailable': 'مزود Eino غير متاح حاليًا. أعد المحاولة بعد قليل.',
      'einoProviderRoute': 'مسار Eino غير متاح حاليًا. حاول لاحقًا.',
      'einoProviderAuth': 'تعذر التحقق من اتصال Eino حاليًا. حاول لاحقًا.',
      'einoTimeout': 'استغرق الرد وقتًا أطول من المتوقع. أعد المحاولة.',
      'einoRateLimited': 'تم تجاوز حد الاستخدام مؤقتًا. انتظر قليلًا ثم أعد المحاولة.',
      'einoGenericError': 'حدث خطأ أثناء الاتصال بـ Eino. أعد المحاولة.',
      'einoRetry': 'إعادة المحاولة',
      'loginFieldsRequired': 'أدخل الرقم الجامعي وكلمة المرور.',
      'loginFailed': 'تعذر تسجيل الدخول. تحقق من بياناتك وحاول مجددًا.',
      'appName': 'TRINEX',
      'splashTagline': 'كل ما تحتاجه في مكان واحد.',
      'welcome': 'مرحبًا بك في TRINEX 👋',
      'welcomeBack': 'أهلًا بك من جديد 👋',
      'studySpaceReady': 'مساحتك الدراسية أصبحت جاهزة لك.',
      'lecturesFiles': 'محاضرات وملفات',
      'upcomingClasses': 'حصصك القادمة',
      'latestAlerts': 'آخر التنبيهات',
      'market': 'المتجر',
      'engineeringTools': 'أدوات هندسية',
      'homeSubtitle': 'كل ما يخص الكلية والرابطة في مكان واحد.',
      'home': 'الرئيسية',
      'einoWelcome': 'أنا Eino، مساعدك الذكي داخل تطبيق الرابطة. اسألني عن الدراسة أو التطبيق أو أي موضوع عام.',
      'einoHint': 'اكتب رسالتك إلى Eino...',
      'einoHomeSubtitle': 'مساعد ذكي للدراسة والرابطة والأسئلة العامة.',
      'schedule': 'الجدول',
      'department': 'القسم',
      'semester': 'السمستر',
      'scheduleEmpty': 'لا توجد حصص منشورة لهذا الاختيار حاليًا.',
      'materials': 'المواد',
      'materialSearch': 'ابحث عن مادة أو ملف...',
      'more': 'المزيد',
      'news': 'الأخبار',
      'announcements': 'الإعلانات',
      'activities': 'الأنشطة',
      'achievements': 'الإنجازات',
      'favorites': 'المفضلة',
      'recent': 'آخر ما تم فتحه',
      'mostUsed': 'الأكثر استخدامًا',
      'downloads': 'التنزيلات',
      'notifications': 'الإشعارات',
      'settings': 'الإعدادات',
      'about': 'عن الرابطة',
      'student': 'حساب الطالب',
      'studentOptional': 'تسجيل الدخول اختياري، لكنه مطلوب للوصول إلى الخدمات الدراسية.',
      'guest': 'الوضع كزائر',
      'appearance': 'المظهر',
      'language': 'اللغة',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'latestNews': 'آخر الأخبار',
      'latestAnnouncement': 'آخر إعلان',
      'continueLearning': 'متابعة التعلم',
      'seeMore': 'عرض المزيد',
      'connection': 'حالة الخدمات',
      'connected': 'متصل',
      'connectionFailed': 'تعذر الاتصال بالخدمة حاليًا',
      'checkConnection': 'اضغط للتحقق من الاتصال',
      'noData': 'لا توجد بيانات حاليًا.',
      'notReady': 'هذه الخدمة غير متاحة بعد.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'غير متصل',
      'error': 'حدث خطأ',
      'refresh': 'تحديث',
      'lockedMaterials': 'المواد والجدول متاحان بعد تسجيل الطالب.',
      'quickAccess': 'الوصول السريع',
      'allServices': 'كل الخدمات',
      'yourStudy': 'دراستك في مكان واحد',
      'explore': 'استكشف',
      'latestUpdates': 'آخر المستجدات',
      'publishedByAssociation': 'محتوى منشور من الرابطة',
      'viewAll': 'عرض الكل',
      'searchHint': 'ابحث عن المواد، الجداول والخدمات...',
      'searchFilters': 'خيارات البحث',
      'marketSearch': 'ابحث عن أداة هندسية...',
      'marketComingSoon': 'سوق الأدوات الهندسية قريبًا',
      'marketComingSoonSubtitle': 'سيتم ربط السوق ببيانات حقيقية من لوحة التحكم. لن نعرض إعلانات تجريبية على أنها إعلانات حقيقية.',
      'marketTrustNote': 'عند الإطلاق، سيعتمد السوق على بيانات موثوقة وسياسات واضحة للطلاب.',
      'marketPlanTitle': 'كيف سيعمل السوق',
      'marketPlanDashboard': 'إدارة الإعلانات والمحتوى من لوحة التحكم',
      'marketPlanApi': 'مزامنة فورية بين الـAPI والتطبيق',
      'marketPlanStudent': 'حماية وظائف النشر والتفاعل بحساب الطالب',
      'studyProgress': 'تابع تقدمك الدراسي',
      'studyProgressSubtitle': 'تخصصك وموادك والـ XP في لوحة واحدة.',
      'startStudy': 'افتح تجربتك الدراسية',
      'startStudySubtitle': 'سجّل دخولك للوصول إلى المواد والجدول والتقدم.',
      'announcementsSubtitle': 'تنبيهات مهمة من الرابطة',
      'newsSubtitle': 'آخر أخبار الكلية والرابطة',
      'activitiesSubtitle': 'فعاليات ومبادرات جديدة',
      'eino': 'إينو',
      'einoCardTitle': 'مساعدك الذكي داخل TRINEX',
      'startChat': 'ابدأ المحادثة',
      'everythingYouNeed': 'كل ما تحتاجه',
      'recentShort': 'الأخيرة',
      'updateRequired': 'تحديث مطلوب',
      'updateAvailable': 'تحديث جديد متاح',
      'installedVersion': 'الإصدار المثبت: {version}',
      'availableVersion': 'الإصدار المتاح: {version}',
      'forceUpdateMessage': 'يجب تحديث التطبيق للمتابعة لأن هذه النسخة لم تعد مدعومة.',
      'later': 'لاحقًا',
      'updateNow': 'تحديث الآن',
      'automatic': 'تلقائي',
      'materialsLoadError': 'تعذر تحميل المواد.\n{error}',
      'cannotOpenMaterial': 'تعذر فتح الملف، تحقق من الرابط أو اتصال الإنترنت.',
      'materialOpenedExternally': 'تم فتح الملف في التطبيق المناسب على جهازك.',
      'progressNote': 'حدّث تقدمك أثناء الدراسة. التقدم يحفظ على حسابك ولا يمنح XP لمجرد فتح الملف.',
      'progressSaveError': 'تعذر حفظ التقدم.',
      'subjectFallback': 'مادة',
      'fileCount': '{count} ملف',
      'noMaterialFiles': 'لا توجد ملفات لهذا المقرر حاليًا.',
      'noSubjects': 'لا توجد مقررات متاحة لهذا الفصل والتخصص حاليًا.',
      'noPublishedFiles': 'المقررات موجودة، لكن لا توجد ملفات منشورة بعد.',
      'updateCheckFailed': 'تعذر التحقق من التحديث حاليًا.',
      'upToDate': 'أنت تستخدم أحدث إصدار متاح.',
      'updateLinkMissing': 'يتوفر الإصدار {version}، لكن رابط التحديث لم يُضبط بعد.',
      'forceUpdateShort': 'هذا التحديث مطلوب للاستمرار.',
      'versionLabel': 'الإصدار {version}',
      'checkUpdates': 'التحقق من التحديثات',
      'studentAccount': 'حساب الطالب',
      'studySpace': 'مساحتك الدراسية',
      'signInToStudy': 'سجّل الدخول للوصول إلى المواد والجدول والتقدم والشارات.',
      'studentNumber': 'الرقم الجامعي',
      'passwordOrCode': 'كلمة المرور / رمز التحقق',
      'signIn': 'تسجيل الدخول',
      'continueAsGuest': 'العودة كزائر',
      'studentProfile': 'ملفي الدراسي',
      'signOut': 'تسجيل الخروج',
      'studentNumberValue': 'الرقم الجامعي: {number}',
      'studentFallback': 'طالب',
      'studyDashboard': 'لوحتك الدراسية',
      'xpLevel': 'XP والمستوى',
      'level': 'المستوى',
      'xp': 'XP',
      'xpLog': 'سجل XP',
      'xpSubtitle': 'تُمنح النقاط من تقدم دراسي موثّق',
      'noXp': 'لم تحصل على XP بعد. ابدأ التقدم في ملفاتك الدراسية.',
      'xpNextLevel': '{current} / {next} XP للمستوى التالي',
      'xpEvent25': 'إكمال 25٪ من ملف دراسي',
      'xpEvent50': 'إكمال 50٪ من ملف دراسي',
      'xpEvent75': 'إكمال 75٪ من ملف دراسي',
      'xpEventComplete': 'إكمال ملف دراسي',
      'xpEventOther': 'نشاط دراسي',
      'achievementsTitle': 'إنجازاتك',
      'badgesEarned': '{earned} من {total} شارة مكتسبة',
      'badgeCollection': 'مجموعة الشارات',
      'daySunday': 'الأحد',
      'dayMonday': 'الاثنين',
      'dayTuesday': 'الثلاثاء',
      'dayWednesday': 'الأربعاء',
      'dayThursday': 'الخميس',
      'dayFriday': 'الجمعة',
      'daySaturday': 'السبت',
      'dayUnknown': 'اليوم {day}',
      'materialsStudentSubtitle': 'مواد القسم والفصل المرتبط بحسابك',
      'scheduleStudentSubtitle': 'جدول قسمك وفصلك الحالي',
      'progressStudentSubtitle': 'تابع تقدمك في الملفات',
      'badgesStudentSubtitle': 'إنجازاتك الدراسية',
      'xpLoadError': 'تعذر تحميل نقاط XP.',
      'badgesLoadError': 'تعذر تحميل الشارات.',
      'einoTitle': 'إينو',
      'newChat': 'محادثة جديدة',
      'einoHistory': 'محادثات Eino',
      'einoOnline': 'متصل الآن',
      'einoAttach': 'إرفاق',
      'einoAttachImage': 'صورة',
      'einoVisionSubtitle': 'حلّل صورة مع Eino',
      'einoAttachDocument': 'مستند',
      'einoDocumentSubtitle': 'PDF أو DOCX أو TXT',
      'einoVoice': 'تسجيل صوتي',
      'einoStopRecording': 'إيقاف التسجيل',
      'einoMicPermission': 'اسمح للتطبيق باستخدام الميكروفون للتسجيل.',
      'einoProcessing': 'جارٍ المعالجة…',
      'einoListen': 'استمع إلى الرد',
      'einoNoHistory': 'لا توجد محادثات سابقة بعد.',
      'send': 'إرسال',
      'einoGreeting': 'أنا إينو ✨',
      'withYou': 'موجودة معك في {section}',
      'suggestions': 'اقتراحات مناسبة لك',
      'sourceHome': 'الرئيسية',
      'sourceMaterials': 'المواد الدراسية',
      'sourceSchedule': 'الجدول',
      'sourceProgress': 'التقدم الدراسي',
      'sourceXp': 'نقاط XP',
      'sourceBadges': 'الشارات',
      'sourceStudent': 'حساب الطالب',
      'suggestStudyPlan': 'ساعديني أرتب مذاكرتي',
      'suggestExplainMaterial': 'اشرحي لي مفهومًا من المادة',
      'suggestStartFile': 'كيف أبدأ بهذا الملف؟',
      'suggestOrganizeDay': 'رتبي لي يومي الدراسي',
      'suggestPrepareClass': 'كيف أستعد للحصة القادمة؟',
      'suggestReviewTime': 'اقترحي لي وقتًا للمراجعة',
      'suggestImproveProgress': 'كيف أحسن تقدمي؟',
      'suggestReviewPlan': 'ساعديني بخطة مراجعة',
      'suggestKeepGoing': 'كيف أستمر بدون ضغط؟',
      'suggestEarnXp': 'كيف أكسب XP من الدراسة؟',
      'suggestProgressMethod': 'ما أفضل طريقة للتقدم؟',
      'suggestStudyGoal': 'ساعديني أضع هدفًا دراسيًا',
      'suggestBadges': 'كيف أحقق الشارات؟',
      'suggestNearbyGoal': 'اقترحي لي هدفًا قريبًا',
      'suggestKeepProgress': 'كيف أحافظ على تقدمي؟',
      'suggestStudy': '📚 ساعديني في الدراسة',
      'suggestDay': '🗓️ ساعديني في يومي',
      'suggestConcept': '💡 اشرحي لي مفهومًا',
      'suggestApp': '🔎 ساعديني في التطبيق',
      'progressLoadError': 'تعذر تحميل تقدمك الدراسي.',
      'progressSummary': 'ملخص التقدم',
      'progressRealActivity': 'تقدمك يُحتسب من نشاط دراسي حقيقي',
      'filesStarted': 'ملفات بدأت',
      'filesCompleted': 'مكتملة',
      'activeMinutes': 'دقائق نشطة',
      'recentFiles': 'ملفاتك الأخيرة',
      'noProgress': 'لا يوجد تقدم مسجل بعد. ابدأ من المواد الدراسية.',
      'studyFile': 'ملف دراسي',
      'completed': 'مكتمل',
      'inProgress': 'قيد الدراسة',
      'badgesTitle': 'الشارات',
      'semesterFallback': 'الفصل {number}',
      'sessionInitializing': 'جارٍ تهيئة جلسة الطالب.',
      'retry': 'إعادة المحاولة',
      'studentServices': 'الخدمات الدراسية',
      'studentServicesLockedTitle': 'سجّل الدخول للوصول إلى خدماتك الدراسية',
      'studentServicesLockedSubtitle': 'المواد والجدول والتقدم والشارات مرتبطة بحساب الطالب.',
      'xpValue': '{value} XP',
      'levelValue': 'المستوى {level}',
      'notificationsCenter': 'مركز الإشعارات',
      'unreadCount': '{count} إشعار غير مقروء',
      'allNotifications': 'الكل',
      'unreadNotifications': 'غير مقروءة',
      'noUnreadNotifications': 'لا توجد إشعارات غير مقروءة.',
    },
    'en': {
      'einoProviderBusy': 'The AI provider is busy right now. Wait a moment and try again.',
      'einoProviderUnavailable': 'Eino’s provider is currently unavailable. Please try again shortly.',
      'einoProviderRoute': 'Eino’s route is currently unavailable. Please try again later.',
      'einoProviderAuth': 'Eino could not verify its provider connection. Please try again later.',
      'einoTimeout': 'The response took longer than expected. Try again.',
      'einoRateLimited': 'Usage is temporarily limited. Wait a moment and try again.',
      'einoGenericError': 'Something went wrong while connecting to Eino. Try again.',
      'einoRetry': 'Retry',
      'loginFieldsRequired': 'Enter your student number and password.',
      'loginFailed': 'Sign-in failed. Check your details and try again.',
      'appName': 'TRINEX',
      'splashTagline': 'Everything you need in one place.',
      'welcome': 'Welcome to TRINEX 👋',
      'welcomeBack': 'Welcome back 👋',
      'studySpaceReady': 'Your study space is ready.',
      'lecturesFiles': 'Lectures and files',
      'upcomingClasses': 'Upcoming classes',
      'latestAlerts': 'Latest alerts',
      'market': 'Marketplace',
      'engineeringTools': 'Engineering tools',
      'homeSubtitle': 'Everything you need from the faculty and association in one place.',
      'home': 'Home',
      'einoWelcome': 'I’m Eino, the smart assistant inside the association app. Ask about study, the app, or general topics.',
      'einoHint': 'Message Eino...',
      'einoHomeSubtitle': 'A smart assistant for study, the association, and general questions.',
      'schedule': 'Schedule',
      'department': 'Department',
      'semester': 'Semester',
      'scheduleEmpty': 'No published classes are available for this selection.',
      'materials': 'Materials',
      'materialSearch': 'Search for a subject or file...',
      'more': 'More',
      'news': 'News',
      'announcements': 'Announcements',
      'activities': 'Activities',
      'achievements': 'Achievements',
      'favorites': 'Favorites',
      'recent': 'Recently opened',
      'mostUsed': 'Most used',
      'downloads': 'Downloads',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'about': 'About',
      'student': 'Student account',
      'studentOptional': 'Sign-in is optional, but required for study services.',
      'guest': 'Guest mode',
      'appearance': 'Appearance',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'latestNews': 'Latest news',
      'latestAnnouncement': 'Latest announcement',
      'continueLearning': 'Continue learning',
      'seeMore': 'See more',
      'connection': 'Service status',
      'connected': 'Connected',
      'connectionFailed': 'The service is currently unavailable',
      'checkConnection': 'Tap to check the connection',
      'noData': 'No data available right now.',
      'notReady': 'This service is not available yet.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'Offline',
      'error': 'Something went wrong',
      'refresh': 'Refresh',
      'lockedMaterials': 'Materials and schedule are available after student sign-in.',
      'quickAccess': 'Quick access',
      'allServices': 'All services',
      'yourStudy': 'Your study in one place',
      'explore': 'Explore',
      'latestUpdates': 'Latest updates',
      'publishedByAssociation': 'Published by the association',
      'viewAll': 'View all',
      'searchHint': 'Search materials, schedules and services...',
      'searchFilters': 'Search filters',
      'marketSearch': 'Search engineering tools...',
      'marketComingSoon': 'Engineering marketplace coming soon',
      'marketComingSoonSubtitle': 'The marketplace will be connected to real Dashboard data. We will not present demo listings as real listings.',
      'marketTrustNote': 'At launch, the marketplace will use trusted data and clear student policies.',
      'marketPlanTitle': 'How the marketplace will work',
      'marketPlanDashboard': 'Manage listings and content from the Dashboard',
      'marketPlanApi': 'Live synchronization between the API and the app',
      'marketPlanStudent': 'Protect publishing and interactions with student accounts',
      'studyProgress': 'Continue your study progress',
      'studyProgressSubtitle': 'Your specialty, materials and XP in one place.',
      'startStudy': 'Start your study experience',
      'startStudySubtitle': 'Sign in to access materials, schedule and progress.',
      'announcementsSubtitle': 'Important association alerts',
      'newsSubtitle': 'Latest faculty and association news',
      'activitiesSubtitle': 'New events and initiatives',
      'eino': 'Eino',
      'einoCardTitle': 'Your smart assistant inside TRINEX',
      'startChat': 'Start chat',
      'everythingYouNeed': 'Everything you need',
      'recentShort': 'Recent',
      'updateRequired': 'Update required',
      'updateAvailable': 'New update available',
      'installedVersion': 'Installed version: {version}',
      'availableVersion': 'Available version: {version}',
      'forceUpdateMessage': 'You must update the app to continue because this version is no longer supported.',
      'later': 'Later',
      'updateNow': 'Update now',
      'automatic': 'Automatic',
      'materialsLoadError': 'Could not load materials.\n{error}',
      'cannotOpenMaterial': 'Could not open the file. Check the link or your internet connection.',
      'materialOpenedExternally': 'The file was opened in the appropriate app on your device.',
      'progressNote': 'Update your progress while studying. Progress is saved to your account; opening a file alone does not grant XP.',
      'progressSaveError': 'Could not save your progress.',
      'subjectFallback': 'Subject',
      'fileCount': '{count} files',
      'noMaterialFiles': 'No files are available for this subject yet.',
      'noSubjects': 'No subjects are available for this semester and specialty yet.',
      'noPublishedFiles': 'Subjects exist, but no files have been published yet.',
      'updateCheckFailed': 'Could not check for updates right now.',
      'upToDate': 'You are using the latest available version.',
      'updateLinkMissing': 'Version {version} is available, but its update link is not configured.',
      'forceUpdateShort': 'This update is required to continue.',
      'versionLabel': 'Version {version}',
      'checkUpdates': 'Check for updates',
      'studentAccount': 'Student account',
      'studySpace': 'Your study space',
      'signInToStudy': 'Sign in to access materials, schedule, progress and badges.',
      'studentNumber': 'University number',
      'passwordOrCode': 'Password / verification code',
      'signIn': 'Sign in',
      'continueAsGuest': 'Continue as guest',
      'studentProfile': 'My student profile',
      'signOut': 'Sign out',
      'studentNumberValue': 'University number: {number}',
      'studentFallback': 'Student',
      'studyDashboard': 'Study dashboard',
      'xpLevel': 'XP & level',
      'level': 'Level',
      'xp': 'XP',
      'xpLog': 'XP history',
      'xpSubtitle': 'Points are awarded from verified study progress',
      'noXp': 'No XP yet. Start progressing through your study files.',
      'xpNextLevel': '{current} / {next} XP to next level',
      'xpEvent25': 'Complete 25% of a study file',
      'xpEvent50': 'Complete 50% of a study file',
      'xpEvent75': 'Complete 75% of a study file',
      'xpEventComplete': 'Complete a study file',
      'xpEventOther': 'Study activity',
      'achievementsTitle': 'Your achievements',
      'badgesEarned': '{earned} of {total} badges earned',
      'badgeCollection': 'Badge collection',
      'daySunday': 'Sunday',
      'dayMonday': 'Monday',
      'dayTuesday': 'Tuesday',
      'dayWednesday': 'Wednesday',
      'dayThursday': 'Thursday',
      'dayFriday': 'Friday',
      'daySaturday': 'Saturday',
      'dayUnknown': 'Day {day}',
      'materialsStudentSubtitle': 'Materials for your department and linked semester',
      'scheduleStudentSubtitle': 'Your department and current semester schedule',
      'progressStudentSubtitle': 'Track your progress through files',
      'badgesStudentSubtitle': 'Your study achievements',
      'xpLoadError': 'Could not load XP.',
      'badgesLoadError': 'Could not load badges.',
      'einoTitle': 'Eino',
      'newChat': 'New chat',
      'einoHistory': 'Eino chats',
      'einoOnline': 'Online now',
      'einoAttach': 'Attach',
      'einoAttachImage': 'Image',
      'einoVisionSubtitle': 'Analyze an image with Eino',
      'einoAttachDocument': 'Document',
      'einoDocumentSubtitle': 'PDF, DOCX or TXT',
      'einoVoice': 'Voice input',
      'einoStopRecording': 'Stop recording',
      'einoMicPermission': 'Allow microphone access to record audio.',
      'einoProcessing': 'Processing…',
      'einoListen': 'Listen to response',
      'einoNoHistory': 'No previous chats yet.',
      'send': 'Send',
      'einoGreeting': 'I’m Eino ✨',
      'withYou': 'I’m with you in {section}',
      'suggestions': 'Suggestions for you',
      'sourceHome': 'Home',
      'sourceMaterials': 'Study materials',
      'sourceSchedule': 'Schedule',
      'sourceProgress': 'Study progress',
      'sourceXp': 'XP',
      'sourceBadges': 'Badges',
      'sourceStudent': 'Student account',
      'suggestStudyPlan': 'Help me plan my study',
      'suggestExplainMaterial': 'Explain a concept from my material',
      'suggestStartFile': 'How should I start this file?',
      'suggestOrganizeDay': 'Organize my study day',
      'suggestPrepareClass': 'How should I prepare for my next class?',
      'suggestReviewTime': 'Suggest a review time',
      'suggestImproveProgress': 'How can I improve my progress?',
      'suggestReviewPlan': 'Help me make a review plan',
      'suggestKeepGoing': 'How can I keep going without pressure?',
      'suggestEarnXp': 'How do I earn XP from studying?',
      'suggestProgressMethod': 'What is a good way to progress?',
      'suggestStudyGoal': 'Help me set a study goal',
      'suggestBadges': 'How do I earn badges?',
      'suggestNearbyGoal': 'Suggest a nearby goal',
      'suggestKeepProgress': 'How do I maintain my progress?',
      'suggestStudy': '📚 Help me study',
      'suggestDay': '🗓️ Help me plan my day',
      'suggestConcept': '💡 Explain a concept',
      'suggestApp': '🔎 Help me use the app',
      'progressLoadError': 'Could not load your study progress.',
      'progressSummary': 'Progress summary',
      'progressRealActivity': 'Your progress is based on real study activity',
      'filesStarted': 'Files started',
      'filesCompleted': 'Completed',
      'activeMinutes': 'Active minutes',
      'recentFiles': 'Your recent files',
      'noProgress': 'No progress recorded yet. Start from study materials.',
      'studyFile': 'Study file',
      'completed': 'Completed',
      'inProgress': 'In progress',
      'badgesTitle': 'Badges',
      'semesterFallback': 'Semester {number}',
      'sessionInitializing': 'Initializing the student session.',
      'retry': 'Retry',
      'studentServices': 'Study services',
      'studentServicesLockedTitle': 'Sign in to access your study services',
      'studentServicesLockedSubtitle': 'Materials, schedule, progress and badges are linked to your student account.',
      'xpValue': '{value} XP',
      'levelValue': 'Level {level}',
      'notificationsCenter': 'Notifications center',
      'unreadCount': '{count} unread notifications',
      'allNotifications': 'All',
      'unreadNotifications': 'Unread',
      'noUnreadNotifications': 'There are no unread notifications.',
    },
    'fr': {
      'einoProviderBusy': 'Le fournisseur IA est occupé. Attendez un instant puis réessayez.',
      'einoProviderUnavailable': 'Le fournisseur d’Eino est indisponible pour le moment. Réessayez bientôt.',
      'einoProviderRoute': 'Le routage d’Eino est indisponible pour le moment. Réessayez plus tard.',
      'einoProviderAuth': 'Eino n’a pas pu vérifier sa connexion au fournisseur. Réessayez plus tard.',
      'einoTimeout': 'La réponse prend plus de temps que prévu. Réessayez.',
      'einoRateLimited': 'L’utilisation est temporairement limitée. Attendez un instant puis réessayez.',
      'einoGenericError': 'Une erreur est survenue lors de la connexion à Eino. Réessayez.',
      'einoRetry': 'Réessayer',
      'loginFieldsRequired': 'Saisissez votre numéro étudiant et votre mot de passe.',
      'loginFailed': 'La connexion a échoué. Vérifiez vos informations et réessayez.',
      'appName': 'TRINEX',
      'splashTagline': 'Tout ce dont vous avez besoin, au même endroit.',
      'welcome': 'Bienvenue sur TRINEX 👋',
      'welcomeBack': 'Bon retour 👋',
      'studySpaceReady': 'Votre espace d’étude est prêt.',
      'lecturesFiles': 'Cours et fichiers',
      'upcomingClasses': 'Cours à venir',
      'latestAlerts': 'Dernières alertes',
      'market': 'Boutique',
      'engineeringTools': 'Outils d’ingénierie',
      'homeSubtitle': 'Tout ce qui concerne la faculté et l’association au même endroit.',
      'home': 'Accueil',
      'einoWelcome': 'Je suis Eino, l’assistant intelligent de l’application. Posez vos questions sur les études, l’association ou des sujets généraux.',
      'einoHint': 'Écrivez à Eino...',
      'einoHomeSubtitle': 'Un assistant intelligent pour les études, l’association et les questions générales.',
      'schedule': 'Emploi du temps',
      'department': 'Département',
      'semester': 'Semestre',
      'scheduleEmpty': 'Aucun cours publié pour cette sélection.',
      'materials': 'Supports',
      'materialSearch': 'Rechercher une matière ou un fichier...',
      'more': 'Plus',
      'news': 'Actualités',
      'announcements': 'Annonces',
      'activities': 'Activités',
      'achievements': 'Réalisations',
      'favorites': 'Favoris',
      'recent': 'Récemment ouverts',
      'mostUsed': 'Les plus utilisés',
      'downloads': 'Téléchargements',
      'notifications': 'Notifications',
      'settings': 'Paramètres',
      'about': 'À propos',
      'student': 'Compte étudiant',
      'studentOptional': 'La connexion est facultative, mais requise pour les services d’étude.',
      'guest': 'Mode invité',
      'appearance': 'Apparence',
      'language': 'Langue',
      'system': 'Système',
      'light': 'Clair',
      'dark': 'Sombre',
      'latestNews': 'Dernières actualités',
      'latestAnnouncement': 'Dernière annonce',
      'continueLearning': 'Continuer l’apprentissage',
      'seeMore': 'Voir plus',
      'connection': 'État du service',
      'connected': 'Connecté',
      'connectionFailed': 'Service actuellement indisponible',
      'checkConnection': 'Touchez pour vérifier la connexion',
      'noData': 'Aucune donnée disponible pour le moment.',
      'notReady': 'Ce service n’est pas encore disponible.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'Hors ligne',
      'error': 'Une erreur est survenue',
      'refresh': 'Actualiser',
      'lockedMaterials': 'Les supports et l’emploi du temps sont disponibles après connexion.',
      'quickAccess': 'Accès rapide',
      'allServices': 'Tous les services',
      'yourStudy': 'Vos études au même endroit',
      'explore': 'Explorer',
      'latestUpdates': 'Dernières mises à jour',
      'publishedByAssociation': 'Publié par l’association',
      'viewAll': 'Tout voir',
      'searchHint': 'Rechercher des supports, horaires et services...',
      'searchFilters': 'Filtres de recherche',
      'marketSearch': 'Rechercher des outils d’ingénierie...',
      'marketComingSoon': 'La boutique d’outils d’ingénierie arrive bientôt',
      'marketComingSoonSubtitle': 'La boutique sera connectée aux vraies données du Dashboard. Aucun contenu de démonstration ne sera présenté comme réel.',
      'marketTrustNote': 'Au lancement, la boutique utilisera des données fiables et des règles étudiantes claires.',
      'marketPlanTitle': 'Fonctionnement prévu',
      'marketPlanDashboard': 'Gérer les annonces et le contenu depuis le Dashboard',
      'marketPlanApi': 'Synchronisation en direct entre l’API et l’application',
      'marketPlanStudent': 'Protéger la publication et les interactions par le compte étudiant',
      'studyProgress': 'Continuer vos études',
      'studyProgressSubtitle': 'Votre spécialité, vos supports et vos XP au même endroit.',
      'startStudy': 'Commencer votre expérience',
      'startStudySubtitle': 'Connectez-vous pour accéder aux supports, horaires et progrès.',
      'announcementsSubtitle': 'Alertes importantes de l’association',
      'newsSubtitle': 'Dernières nouvelles de la faculté et de l’association',
      'activitiesSubtitle': 'Nouveaux événements et initiatives',
      'eino': 'Eino',
      'einoCardTitle': 'Votre assistant intelligent dans TRINEX',
      'startChat': 'Démarrer la conversation',
      'everythingYouNeed': 'Tout ce dont vous avez besoin',
      'recentShort': 'Récents',
      'updateRequired': 'Mise à jour requise',
      'updateAvailable': 'Nouvelle mise à jour disponible',
      'installedVersion': 'Version installée : {version}',
      'availableVersion': 'Version disponible : {version}',
      'forceUpdateMessage': 'Vous devez mettre à jour l’application pour continuer, car cette version n’est plus prise en charge.',
      'later': 'Plus tard',
      'updateNow': 'Mettre à jour',
      'automatic': 'Automatique',
      'materialsLoadError': 'Impossible de charger les supports.\n{error}',
      'cannotOpenMaterial': 'Impossible d’ouvrir le fichier. Vérifiez le lien ou votre connexion Internet.',
      'materialOpenedExternally': 'Le fichier a été ouvert dans l’application appropriée sur votre appareil.',
      'progressNote': 'Mettez à jour votre progression pendant vos études. La progression est enregistrée sur votre compte ; ouvrir un fichier seul ne donne pas de XP.',
      'progressSaveError': 'Impossible d’enregistrer la progression.',
      'subjectFallback': 'Matière',
      'fileCount': '{count} fichiers',
      'noMaterialFiles': 'Aucun fichier n’est disponible pour cette matière pour le moment.',
      'noSubjects': 'Aucune matière n’est disponible pour ce semestre et cette spécialité.',
      'noPublishedFiles': 'Les matières existent, mais aucun fichier n’a encore été publié.',
      'updateCheckFailed': 'Impossible de vérifier les mises à jour pour le moment.',
      'upToDate': 'Vous utilisez la dernière version disponible.',
      'updateLinkMissing': 'La version {version} est disponible, mais son lien de mise à jour n’est pas configuré.',
      'forceUpdateShort': 'Cette mise à jour est requise pour continuer.',
      'versionLabel': 'Version {version}',
      'checkUpdates': 'Vérifier les mises à jour',
      'studentAccount': 'Compte étudiant',
      'studySpace': 'Votre espace d’étude',
      'signInToStudy': 'Connectez-vous pour accéder aux supports, horaires, progrès et badges.',
      'studentNumber': 'Numéro universitaire',
      'passwordOrCode': 'Mot de passe / code de vérification',
      'signIn': 'Se connecter',
      'continueAsGuest': 'Continuer en invité',
      'studentProfile': 'Mon profil étudiant',
      'signOut': 'Se déconnecter',
      'studentNumberValue': 'Numéro universitaire : {number}',
      'studentFallback': 'Étudiant',
      'studyDashboard': 'Tableau de bord étudiant',
      'xpLevel': 'XP et niveau',
      'level': 'Niveau',
      'xp': 'XP',
      'xpLog': 'Historique XP',
      'xpSubtitle': 'Les points sont attribués à partir d’une progression d’étude vérifiée',
      'noXp': 'Pas encore de XP. Commencez votre progression dans vos fichiers d’étude.',
      'xpNextLevel': '{current} / {next} XP pour le niveau suivant',
      'xpEvent25': 'Terminer 25 % d’un fichier d’étude',
      'xpEvent50': 'Terminer 50 % d’un fichier d’étude',
      'xpEvent75': 'Terminer 75 % d’un fichier d’étude',
      'xpEventComplete': 'Terminer un fichier d’étude',
      'xpEventOther': 'Activité d’étude',
      'achievementsTitle': 'Vos réalisations',
      'badgesEarned': '{earned} sur {total} badges obtenus',
      'badgeCollection': 'Collection de badges',
      'daySunday': 'Dimanche',
      'dayMonday': 'Lundi',
      'dayTuesday': 'Mardi',
      'dayWednesday': 'Mercredi',
      'dayThursday': 'Jeudi',
      'dayFriday': 'Vendredi',
      'daySaturday': 'Samedi',
      'dayUnknown': 'Jour {day}',
      'materialsStudentSubtitle': 'Supports de votre département et semestre associé',
      'scheduleStudentSubtitle': 'Emploi du temps de votre département et semestre actuel',
      'progressStudentSubtitle': 'Suivez votre progression dans les fichiers',
      'badgesStudentSubtitle': 'Vos réalisations d’étude',
      'xpLoadError': 'Impossible de charger les XP.',
      'badgesLoadError': 'Impossible de charger les badges.',
      'einoTitle': 'Eino',
      'newChat': 'Nouvelle conversation',
      'einoHistory': 'Conversations Eino',
      'einoOnline': 'En ligne',
      'einoAttach': 'Joindre',
      'einoAttachImage': 'Image',
      'einoVisionSubtitle': 'Analyser une image avec Eino',
      'einoAttachDocument': 'Document',
      'einoDocumentSubtitle': 'PDF, DOCX ou TXT',
      'einoVoice': 'Entrée vocale',
      'einoStopRecording': 'Arrêter l’enregistrement',
      'einoMicPermission': 'Autorisez le microphone pour enregistrer.',
      'einoProcessing': 'Traitement…',
      'einoListen': 'Écouter la réponse',
      'einoNoHistory': 'Aucune conversation précédente.',
      'send': 'Envoyer',
      'einoGreeting': 'Je suis Eino ✨',
      'withYou': 'Je suis avec vous dans {section}',
      'suggestions': 'Suggestions pour vous',
      'sourceHome': 'Accueil',
      'sourceMaterials': 'Supports d’étude',
      'sourceSchedule': 'Emploi du temps',
      'sourceProgress': 'Progression',
      'sourceXp': 'XP',
      'sourceBadges': 'Badges',
      'sourceStudent': 'Compte étudiant',
      'suggestStudyPlan': 'Aidez-moi à organiser mes études',
      'suggestExplainMaterial': 'Expliquez un concept de mon cours',
      'suggestStartFile': 'Comment commencer ce fichier ?',
      'suggestOrganizeDay': 'Organisez ma journée d’étude',
      'suggestPrepareClass': 'Comment préparer mon prochain cours ?',
      'suggestReviewTime': 'Proposez un moment de révision',
      'suggestImproveProgress': 'Comment améliorer ma progression ?',
      'suggestReviewPlan': 'Aidez-moi à créer un plan de révision',
      'suggestKeepGoing': 'Comment continuer sans pression ?',
      'suggestEarnXp': 'Comment gagner des XP en étudiant ?',
      'suggestProgressMethod': 'Quelle bonne méthode pour progresser ?',
      'suggestStudyGoal': 'Aidez-moi à fixer un objectif d’étude',
      'suggestBadges': 'Comment obtenir des badges ?',
      'suggestNearbyGoal': 'Proposez-moi un objectif proche',
      'suggestKeepProgress': 'Comment maintenir ma progression ?',
      'suggestStudy': '📚 Aidez-moi à étudier',
      'suggestDay': '🗓️ Aidez-moi à organiser ma journée',
      'suggestConcept': '💡 Expliquez un concept',
      'suggestApp': '🔎 Aidez-moi avec l’application',
      'progressLoadError': 'Impossible de charger votre progression.',
      'progressSummary': 'Résumé de la progression',
      'progressRealActivity': 'Votre progression repose sur une activité d’étude réelle',
      'filesStarted': 'Fichiers commencés',
      'filesCompleted': 'Terminés',
      'activeMinutes': 'Minutes actives',
      'recentFiles': 'Vos fichiers récents',
      'noProgress': 'Aucune progression enregistrée. Commencez par les supports d’étude.',
      'studyFile': 'Fichier d’étude',
      'completed': 'Terminé',
      'inProgress': 'En cours',
      'badgesTitle': 'Badges',
      'semesterFallback': 'Semestre {number}',
      'sessionInitializing': 'Initialisation de la session étudiante.',
      'retry': 'Réessayer',
      'studentServices': 'Services d’étude',
      'studentServicesLockedTitle': 'Connectez-vous pour accéder à vos services d’étude',
      'studentServicesLockedSubtitle': 'Les supports, l’emploi du temps, la progression et les badges sont liés à votre compte étudiant.',
      'xpValue': '{value} XP',
      'levelValue': 'Niveau {level}',
      'notificationsCenter': 'Centre des notifications',
      'unreadCount': '{count} notifications non lues',
      'allNotifications': 'Toutes',
      'unreadNotifications': 'Non lues',
      'noUnreadNotifications': 'Aucune notification non lue.',
    },
  };

  String t(String key, [Map<String, String>? params]) {
    var value = _values[locale.languageCode]?[key] ?? _values['ar']![key] ?? key;
    if (params != null) {
      for (final entry in params.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales
          .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
