import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';



class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('ar'),
    Locale('en'),
    Locale('fr'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const _values = <String, Map<String, String>>{
    'ar': {
      'einoProviderBusy': 'مزود الذكاء الاصطناعي مشغول حاليًا. انتظر قليلًا ثم أعد المحاولة.',
      'einoProviderUnavailable': 'مزود Eino غير متاح حاليًا. أعد المحاولة بعد قليل.',
      'einoProviderRoute': 'مسار Eino غير متاح حاليًا. حاول لاحقًا.',
      'einoProviderAuth': 'تعذر التحقق من اتصال Eino حاليًا. حاول لاحقًا.',
      'einoTimeout': 'استغرق الرد وقتًا أطول من المتوقع. أعد المحاولة.',
      'einoRateLimited': 'تم تجاوز حد الاستخدام مؤقتًا. انتظر قليلًا ثم أعد المحاولة.',
      'einoGenericError': 'حدث خطأ أثناء الاتصال بـ Eino. أعد المحاولة.',
      'einoModelsTitle': 'النماذج المحلية',
      'einoModelsSubtitle': 'اختر النموذج الذي ستستخدمه Eino عند تفعيل المحرك المحلي.',
      'einoModelsRuntimePending': 'كتالوج النماذج جاهز، لكن محرك التشغيل والتنزيل المحلي لم يُفعّل بعد. لن يتم تنزيل أي ملف الآن.',
      'einoModelDownloadComing': 'التنزيل سيتوفر مع محرك Offline AI',
      'einoModelSourcePending': 'مصدر هذا النموذج لم يُضبط بعد. لن يبدأ أي تنزيل غير موثوق.',
      'einoModelRamWarning': 'الذاكرة الحرة الحالية أقل من المتطلبات المقترحة لهذا النموذج.',
      'einoModelLoaded': 'تم تحميل النموذج المحلي وأصبح جاهزًا.',
      'einoModelDownloading': 'جاري تنزيل النموذج المحلي…',
      'einoModelDownload': 'تنزيل وتشغيل',
      'einoModelUse': 'تشغيل النموذج',
      'einoModelAndroidOnly': 'المحرك المحلي يعمل حاليًا على Android فقط.',
      'einoModelHardwareReady': 'الجهاز جاهز للمحرك المحلي',
      'einoModelIntegrityFailed': 'ملف النموذج المحلي تالف أو تغيّر. أعد تنزيله.',
      'einoModelBenchmark': 'اختبار سرعة النموذج',
      'einoModelBenchmarkResult': 'سرعة تقريبية: {speed} رمز/ث — أول رمز: {first} مللي ثانية',
      'einoRam': 'RAM',
      'einoRetry': 'إعادة المحاولة',
      'loginFieldsRequired': 'أدخل الرقم الجامعي وكلمة المرور.',
      'loginFailed': 'تعذر تسجيل الدخول. تحقق من بياناتك وحاول مجددًا.',
      'appName': 'TRINEX',
      'splashTagline': 'كل ما تحتاجه في مكان واحد.',
      'welcome': 'مرحبًا بك في TRINEX 👋',
      'welcomeBack': 'أهلًا بك من جديد 👋',
      'studySpaceReady': 'مساحتك الدراسية أصبحت جاهزة لك.',
      'lecturesFiles': 'محاضرات وملفات',
      'upcomingClasses': 'حصصك القادمة',
      'latestAlerts': 'آخر التنبيهات',
      'market': 'المتجر',
      'engineeringTools': 'أدوات هندسية',
      'homeSubtitle': 'كل ما يخص الكلية والرابطة في مكان واحد.',
      'home': 'الرئيسية',
      'einoWelcome': 'أنا Eino، مساعدك الذكي داخل تطبيق الرابطة. اسألني عن الدراسة أو التطبيق أو أي موضوع عام.',
      'einoHint': 'اكتب رسالتك إلى Eino...',
      'einoHomeSubtitle': 'مساعد ذكي للدراسة والرابطة والأسئلة العامة.',
      'yourJourney': 'رحلتك',
      'viewXp': 'تفاصيل XP',
      'viewBadges': 'الشارات',
      'levelReady': 'المستوى جاهز 🎉',
      'levelReadySubtitle': 'أكملت نقاط المستوى الحالي. واصل تقدمك الدراسي.',
      'nextLevelGoal': 'الهدف التالي',
      'xpRemaining': 'تبقى {value} XP للوصول إلى المستوى التالي.',
      'einoGoalHome': 'اسألني عن الدراسة أو التطبيق، وسأساعدك بخطوة عملية.',
      'einoGoalMaterials': 'لنحوّل المادة الحالية إلى خطة مذاكرة بسيطة.',
      'einoGoalSchedule': 'لنرتب يومك الدراسي حول حصصك القادمة.',
      'einoGoalProgress': 'لنراجع تقدمك ونحدد أقرب خطوة مفيدة.',
      'einoGoalXp': 'لنحوّل نقاط XP إلى هدف دراسي واضح.',
      'einoGoalBadges': 'لنحدد أقرب شارة يمكنك تحقيقها بدون ضغط.',
      'schedule': 'الجدول',
      'department': 'القسم',
      'semester': 'السمستر',
      'scheduleEmpty': 'لا توجد حصص منشورة لهذا الاختيار حاليًا.',
      'materials': 'المواد',
      'materialSearch': 'ابحث عن مادة أو ملف...',
      'more': 'المزيد',
      'news': 'الأخبار',
      'media': 'الإعلام',
      'mediaSubtitle': 'الأخبار والفعاليات والأنشطة في مكان واحد.',
      'events': 'الفعاليات',
      'reply': 'رد',
      'writeReply': 'اكتب ردك',
      'commentReactionFailed': 'تعذر تسجيل التفاعل على التعليق.',
      'networkOffline': 'لا يوجد اتصال بالإنترنت.',
      'serverError': 'هناك خطأ في السيرفر. حاول مرة أخرى.',
      'invalidServerResponse': 'استجابة غير صالحة من السيرفر.',
      'all': 'الكل',
      'officialNews': 'بيانات رسمية',
      'openNews': 'فتح تفاصيل الخبر',
      'like': 'إعجاب',
      'liked': 'تم الإعجاب',
      'likeFailed': 'تعذر تسجيل الإعجاب',
      'comments': 'التعليقات',
      'newsDetails': 'تفاصيل الخبر',
      'noComments': 'لا توجد تعليقات بعد.',
      'writeComment': 'اكتب تعليقك',
      'publish': 'نشر',
      'commentPublished': 'تم نشر التعليق',
      'commentFailed': 'تعذر نشر التعليق',
      'settingsSubtitle': 'تخصيص الواجهة والسمات وخيارات العرض',
      'appearanceMode': 'نمط العرض',
      'checking': 'جارٍ الفحص',
      'announcements': 'الإعلانات',
      'activities': 'الأنشطة',
      'achievements': 'الإنجازات',
      'favorites': 'المفضلة',
      'recent': 'آخر ما تم فتحه',
      'mostUsed': 'الأكثر استخدامًا',
      'downloads': 'التنزيلات',
      'notifications': 'الإشعارات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'logoutConfirm': 'هل تريد تسجيل الخروج من حساب الطالب؟',
      'cancel': 'إلغاء',
      'appInfo': 'معلومات التطبيق',
      'about': 'عن الرابطة',
      'student': 'حساب الطالب',
      'studentOptional': 'تسجيل الدخول اختياري، لكنه مطلوب للوصول إلى الخدمات الدراسية.',
      'guest': 'الوضع كزائر',
      'appearance': 'المظهر',
      'language': 'اللغة',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'latestNews': 'آخر الأخبار',
      'latestAnnouncement': 'آخر إعلان',
      'continueLearning': 'متابعة التعلم',
      'seeMore': 'عرض المزيد',
      'connection': 'حالة الخدمات',
      'connected': 'متصل',
      'connectionFailed': 'تعذر الاتصال بالخدمة حاليًا',
      'checkConnection': 'اضغط للتحقق من الاتصال',
      'noData': 'لا توجد بيانات حاليًا.',
      'notReady': 'هذه الخدمة غير متاحة بعد.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'غير متصل',
      'error': 'حدث خطأ',
      'refresh': 'تحديث',
      'lockedMaterials': 'المواد والجدول متاحان بعد تسجيل الطالب.',
      'quickAccess': 'الوصول السريع',
      'allServices': 'كل الخدمات',
      'yourStudy': 'دراستك في مكان واحد',
      'explore': 'استكشف',
      'latestUpdates': 'آخر المستجدات',
      'publishedByAssociation': 'محتوى منشور من الرابطة',
      'viewAll': 'عرض الكل',
      'searchHint': 'ابحث عن المواد، الجداول والخدمات...',
      'searchFilters': 'خيارات البحث',
      'marketSearch': 'ابحث عن أداة هندسية...',
      'marketComingSoon': 'سوق الأدوات الهندسية قريبًا',
      'marketComingSoonSubtitle': 'سيتم ربط السوق ببيانات حقيقية من لوحة التحكم. لن نعرض إعلانات تجريبية على أنها إعلانات حقيقية.',
      'marketTrustNote': 'عند الإطلاق، سيعتمد السوق على بيانات موثوقة وسياسات واضحة للطلاب.',
      'marketPlanTitle': 'كيف سيعمل السوق',
      'marketPlanDashboard': 'إدارة الإعلانات والمحتوى من لوحة التحكم',
      'marketPlanApi': 'مزامنة فورية بين الـAPI والتطبيق',
      'marketPlanStudent': 'حماية وظائف النشر والتفاعل بحساب الطالب',
      'studyProgress': 'تابع تقدمك الدراسي',
      'studyProgressSubtitle': 'تخصصك وموادك والـ XP في لوحة واحدة.',
      'startStudy': 'افتح تجربتك الدراسية',
      'startStudySubtitle': 'سجّل دخولك للوصول إلى المواد والجدول والتقدم.',
      'announcementsSubtitle': 'تنبيهات مهمة من الرابطة',
      'newsSubtitle': 'آخر أخبار الكلية والرابطة',
      'activitiesSubtitle': 'فعاليات ومبادرات جديدة',
      'eino': 'إينو',
      'einoCardTitle': 'مساعدك الذكي داخل TRINEX',
      'startChat': 'ابدأ المحادثة',
      'everythingYouNeed': 'كل ما تحتاجه',
      'recentShort': 'الأخيرة',
      'updateRequired': 'تحديث مطلوب',
      'updateAvailable': 'تحديث جديد متاح',
      'installedVersion': 'الإصدار المثبت: {version}',
      'availableVersion': 'الإصدار المتاح: {version}',
      'forceUpdateMessage': 'يجب تحديث التطبيق للمتابعة لأن هذه النسخة لم تعد مدعومة.',
      'later': 'لاحقًا',
      'updateNow': 'تحديث الآن',
      'automatic': 'تلقائي',
      'materialsLoadError': 'تعذر تحميل المواد.\n{error}',
      'cannotOpenMaterial': 'تعذر فتح الملف، تحقق من الرابط أو اتصال الإنترنت.',
      'materialOpenedExternally': 'تم فتح الملف في التطبيق المناسب على جهازك.',
      'progressNote': 'حدّث تقدمك أثناء الدراسة. التقدم يحفظ على حسابك ولا يمنح XP لمجرد فتح الملف.',
      'progressSaveError': 'تعذر حفظ التقدم.',
      'subjectFallback': 'مادة',
      'fileCount': '{count} ملف',
      'noMaterialFiles': 'لا توجد ملفات لهذا المقرر حاليًا.',
      'noSubjects': 'لا توجد مقررات متاحة لهذا الفصل والتخصص حاليًا.',
      'noPublishedFiles': 'المقررات موجودة، لكن لا توجد ملفات منشورة بعد.',
      'updateCheckFailed': 'تعذر التحقق من التحديث حاليًا.',
      'upToDate': 'أنت تستخدم أحدث إصدار متاح.',
      'updateLinkMissing': 'يتوفر الإصدار {version}، لكن رابط التحديث لم يُضبط بعد.',
      'forceUpdateShort': 'هذا التحديث مطلوب للاستمرار.',
      'versionLabel': 'الإصدار {version}',
      'checkUpdates': 'التحقق من التحديثات',
      'studentAccount': 'حساب الطالب',
      'studySpace': 'مساحتك الدراسية',
      'signInToStudy': 'سجّل الدخول للوصول إلى المواد والجدول والتقدم والشارات.',
      'studentNumber': 'الرقم الجامعي',
      'passwordOrCode': 'كلمة المرور / رمز التحقق',
      'signIn': 'تسجيل الدخول',
      'studentProfile': 'ملفي الدراسي',
      'signOut': 'تسجيل الخروج',
      'studentNumberValue': 'الرقم الجامعي: {number}',
      'studentFallback': 'طالب',
      'studyDashboard': 'لوحتك الدراسية',
      'xpLevel': 'XP والمستوى',
      'level': 'المستوى',
      'xp': 'XP',
      'xpLog': 'سجل XP',
      'xpSubtitle': 'تُمنح النقاط من تقدم دراسي موثّق',
      'noXp': 'لم تحصل على XP بعد. ابدأ التقدم في ملفاتك الدراسية.',
      'xpNextLevel': '{current} / {next} XP للمستوى التالي',
      'xpEvent25': 'إكمال 25٪ من ملف دراسي',
      'xpEvent50': 'إكمال 50٪ من ملف دراسي',
      'xpEvent75': 'إكمال 75٪ من ملف دراسي',
      'xpEventComplete': 'إكمال ملف دراسي',
      'xpEventOther': 'نشاط دراسي',
      'achievementsTitle': 'إنجازاتك',
      'badgesEarned': '{earned} من {total} شارة مكتسبة',
      'badgeCollection': 'مجموعة الشارات',
      'daySunday': 'الأحد',
      'dayMonday': 'الاثنين',
      'dayTuesday': 'الثلاثاء',
      'dayWednesday': 'الأربعاء',
      'dayThursday': 'الخميس',
      'dayFriday': 'الجمعة',
      'daySaturday': 'السبت',
      'dayUnknown': 'اليوم {day}',
      'materialsStudentSubtitle': 'مواد القسم والفصل المرتبط بحسابك',
      'scheduleStudentSubtitle': 'جدول قسمك وفصلك الحالي',
      'progressStudentSubtitle': 'تابع تقدمك في الملفات',
      'badgesStudentSubtitle': 'إنجازاتك الدراسية',
      'xpLoadError': 'تعذر تحميل نقاط XP.',
      'badgesLoadError': 'تعذر تحميل الشارات.',
'einoMemoryAdd': 'إضافة ذكرى',
      'einoMemoryAddHint': 'مثال: أفضل الشرح بالأمثلة الهندسية.',
      'einoMemoryCategory': 'التصنيف',
'einoMemoryTitle': 'ذاكرة Eino',
      'einoMemorySubtitle': 'ذكرياتك المحفوظة التي تستخدمها Eino عندما تكون ذات صلة.',
      'einoMemoryEmpty': 'لا توجد ذكريات محفوظة بعد.',
      'einoMemoryForget': 'حذف من الذاكرة',
      'einoOnlineReady': 'Eino متصلة بالذكاء السحابي',
      'einoOfflineMode': 'Eino تعمل بدون اتصال',
      'einoOfflineReady': 'محرك محلي متاح على الجهاز.',
      'einoModel': 'النموذج',
      'einoCheckingCapabilities': 'جارٍ التحقق من قدرات Eino…',
      'einoTitle': 'إينو',
      'newChat': 'محادثة جديدة',
      'einoHistory': 'محادثات Eino',
      'einoOnline': 'متصل الآن',
      'einoAttach': 'إرفاق',
      'einoAttachImage': 'صورة',
      'einoVisionSubtitle': 'حلّل صورة مع Eino',
      'einoAttachDocument': 'مستند',
      'einoDocumentSubtitle': 'PDF أو DOCX أو TXT',
      'einoVoice': 'تسجيل صوتي',
      'einoStopRecording': 'إيقاف التسجيل',
      'einoMicPermission': 'اسمح للتطبيق باستخدام الميكروفون للتسجيل.',
      'einoProcessing': 'جارٍ المعالجة…',
      'einoListen': 'استمع إلى الرد',
      'einoNoHistory': 'لا توجد محادثات سابقة بعد.',
      'send': 'إرسال',
      'copy': 'نسخ',
      'copied': 'تم النسخ',
      'einoGreeting': 'أنا إينو ✨',
      'withYou': 'موجودة معك في {section}',
      'suggestions': 'اقتراحات مناسبة لك',
      'sourceHome': 'الرئيسية',
      'sourceMaterials': 'المواد الدراسية',
      'sourceSchedule': 'الجدول',
      'sourceProgress': 'التقدم الدراسي',
      'sourceXp': 'نقاط XP',
      'sourceBadges': 'الشارات',
      'sourceStudent': 'حساب الطالب',
      'suggestStudyPlan': 'ساعديني أرتب مذاكرتي',
      'suggestExplainMaterial': 'اشرحي لي مفهومًا من المادة',
      'suggestStartFile': 'كيف أبدأ بهذا الملف؟',
      'suggestOrganizeDay': 'رتبي لي يومي الدراسي',
      'suggestPrepareClass': 'كيف أستعد للحصة القادمة؟',
      'suggestReviewTime': 'اقترحي لي وقتًا للمراجعة',
      'suggestImproveProgress': 'كيف أحسن تقدمي؟',
      'suggestReviewPlan': 'ساعديني بخطة مراجعة',
      'suggestKeepGoing': 'كيف أستمر بدون ضغط؟',
      'suggestEarnXp': 'كيف أكسب XP من الدراسة؟',
      'suggestProgressMethod': 'ما أفضل طريقة للتقدم؟',
      'suggestStudyGoal': 'ساعديني أضع هدفًا دراسيًا',
      'suggestBadges': 'كيف أحقق الشارات؟',
      'suggestNearbyGoal': 'اقترحي لي هدفًا قريبًا',
      'suggestKeepProgress': 'كيف أحافظ على تقدمي؟',
      'suggestStudy': '📚 ساعديني في الدراسة',
      'suggestDay': '🗓️ ساعديني في يومي',
      'suggestConcept': '💡 اشرحي لي مفهومًا',
      'suggestApp': '🔎 ساعديني في التطبيق',
      'progressLoadError': 'تعذر تحميل تقدمك الدراسي.',
      'progressSummary': 'ملخص التقدم',
      'progressRealActivity': 'تقدمك يُحتسب من نشاط دراسي حقيقي',
      'filesStarted': 'ملفات بدأت',
      'filesCompleted': 'مكتملة',
      'activeMinutes': 'دقائق نشطة',
      'recentFiles': 'ملفاتك الأخيرة',
      'noProgress': 'لا يوجد تقدم مسجل بعد. ابدأ من المواد الدراسية.',
      'studyFile': 'ملف دراسي',
      'completed': 'مكتمل',
      'inProgress': 'قيد الدراسة',
      'badgesTitle': 'الشارات',
      'semesterFallback': 'الفصل {number}',
      'sessionInitializing': 'جارٍ تهيئة جلسة الطالب.',
      'retry': 'إعادة المحاولة',
      'studentServices': 'الخدمات الدراسية',
      'studentServicesLockedTitle': 'سجّل الدخول للوصول إلى خدماتك الدراسية',
      'studentServicesLockedSubtitle': 'المواد والجدول والتقدم والشارات مرتبطة بحساب الطالب.',
      'xpValue': '{value} XP',
      'levelValue': 'المستوى {level}',
      'notificationsCenter': 'مركز الإشعارات',
      'unreadCount': '{count} إشعار غير مقروء',
      'allNotifications': 'الكل',
      'unreadNotifications': 'غير مقروءة',
      'noUnreadNotifications': 'لا توجد إشعارات غير مقروءة.',
      'onboardingTitle1': 'منصتك الأكاديمية المتكاملة',
      'onboardingDesc1': 'محاضرات، ملخصات، ومراجع مقسمة حسب تخصصك الهندسي وفصلك الدراسي الحالي.',
      'onboardingSubtitle1': 'محاضرات، ملخصات، ومراجع مقسمة حسب تخصصك الهندسي وفصلك الدراسي الحالي.',
      'onboardingTitle2': 'Eino — مساعدتك الذكية',
      'onboardingDesc2': 'شخصية تفاعلية تجيب على استفساراتك، تنظم يومك، وتساعدك في فهم المفاهيم الهندسية.',
      'onboardingSubtitle2': 'شخصية تفاعلية تجيب على استفساراتك، تنظم يومك، وتساعدك في فهم المفاهيم الهندسية.',
      'onboardingTitle3': 'مجتمع كلية الهندسة والعمارة',
      'onboardingDesc3': 'متابعة أحدث الإعلانات الرسمية، فعاليات الرابطة، والأدوات الهندسية لحظة بلحظة.',
      'onboardingSubtitle3': 'متابعة أحدث الإعلانات الرسمية، فعاليات الرابطة، والأدوات الهندسية لحظة بلحظة.',
      'createAccount': 'إنشاء حساب جديد',
      'continueAsGuest': 'المتابعة كزائر',
      'skip': 'تخطي',
      'next': 'التالي',
      'startNow': 'ابدأ الآن',
      'getStarted': 'ابدأ الآن',
      'guestNoticeTitle': 'التصفح بوضع الزائر',
      'guestNoticeDesc': 'المتابعة كزائر تتيح لك استعراض الأخبار، الأنشطة، الأدوات الهندسية، والمحادثة مع Eino. للوصول للمواد والجداول يرجى تسجيل حساب طالب.',
      'understood': 'فهمت ذلك',
      'registerTitle': 'تسجيل طالب جديد',
      'registerSubtitle': 'أنشئ حسابك الأكاديمي للوصول إلى موادك وجدولك الفصلي.',
      'academicId': 'الرقم الجامعي',
      'academicIdHint': 'مثال: 20210045',
      'academicIdHelp': 'الرقم المسجل في قيود كلية الهندسة والعمارة.',
      'selectDepartment': 'التخصص الأكاديمي',
      'departmentLockedHelp': 'التخصص ثابت بعد التسجيل ولا يمكن تعديله إلا عبر الرابطة.',
      'selectSemester': 'الفصل الدراسي',
      'semesterFlexibleHelp': 'يمكنك تعديل الفصل الدراسي بسهولة لاحقًا من الإعدادات.',
      'email': 'البريد الإلكتروني',
      'emailHint': 'student@domain.edu',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'passwordMismatch': 'كلمتا المرور غير متطابقتين.',
      'passwordTooShort': 'كلمة المرور يجب ألا تقل عن 8 أحرف.',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'dontHaveAccount': 'طالب جديد؟',
      'accentColor': 'لون المظهر',
      'replayOnboarding': 'عرض شاشات التعريف (Onboarding)',
      'updateSemesterTitle': 'تعديل الفصل الدراسي الحالي',
      'semesterUpdatedSuccess': 'تم تحديث فصلك الدراسي بنجاح.',
      'changeSemester': 'تغيير الفصل',
      'studentLockedCardTitle': 'محتوى دراسي مخصص للطلاب',
      'studentLockedCardDesc': 'سجّل دخولك أو أنشئ حسابك لتصفح مقررات وجداول تخصصك وفصلك الدراسي.',
      'unitConverter': 'محول الوحدات الهندسية',
      'gpaCalculator': 'حاسبة المعدل التراكمي',
      'resistorCalculator': 'حاسبة ألوان المقاومات',
      'engineeringReferences': 'المراجع والقوانين الهندسية',
      'unitConverterTitle': 'محول الوحدات الهندسية',
      'gpaCalculatorTitle': 'حاسبة المعدل التراكمي',
      'resistorDecoderTitle': 'حاسبة ألوان المقاومات',
      'engineeringRefsTitle': 'المراجع والقوانين الهندسية',
      'toolsTitle': 'الأدوات الهندسية',
      'toolsSubtitle': 'مجموعة أدوات عملية ومفيدة لطلاب الهندسة والعمارة.',
      'value': 'القيمة',
      'from': 'من',
      'to': 'إلى',
      'result': 'النتيجة',
      'calculate': 'حساب',
      'courses': 'المقررات',
      'grade': 'التقدير',
      'credits': 'الساعات',
      'gpaResult': 'المعدل المحسوب: {gpa}',
      'todaySchedule': 'جدول اليوم',
      'noClassesToday': 'لا توجد محاضرات مجدولة لهذا اليوم.',
      'viewFullSchedule': 'عرض الجدول الكامل',
      'myMaterials': 'موادي الدراسية',
      'quickPromptEino': 'اسأل Eino أي سؤال...',
      'guestWelcomeTitle': 'مرحبًا بك في TRINEX',
      'guestWelcomeSubtitle': 'المنصة الطلابية الرسمية لكلية الهندسة والعمارة',
      'guestBannerNotice': 'أنت تتصفح كزائر. سجّل دخولك للوصول إلى مقرراتك وجداولك الدراسية.',
    },
    'en': {
      'einoProviderBusy': 'The AI provider is busy right now. Wait a moment and try again.',
      'einoProviderUnavailable': 'Eino’s provider is currently unavailable. Please try again shortly.',
      'einoProviderRoute': 'Eino’s route is currently unavailable. Please try again later.',
      'einoProviderAuth': 'Eino could not verify its provider connection. Please try again later.',
      'einoTimeout': 'The response took longer than expected. Try again.',
      'einoRateLimited': 'Usage is temporarily limited. Wait a moment and try again.',
      'einoGenericError': 'Something went wrong while connecting to Eino. Try again.',
      'einoRetry': 'Retry',
      'loginFieldsRequired': 'Enter your student number and password.',
      'loginFailed': 'Sign-in failed. Check your details and try again.',
      'appName': 'TRINEX',
      'splashTagline': 'Everything you need in one place.',
      'welcome': 'Welcome to TRINEX 👋',
      'welcomeBack': 'Welcome back 👋',
      'studySpaceReady': 'Your study space is ready.',
      'lecturesFiles': 'Lectures and files',
      'upcomingClasses': 'Upcoming classes',
      'latestAlerts': 'Latest alerts',
      'market': 'Marketplace',
      'engineeringTools': 'Engineering tools',
      'homeSubtitle': 'Everything you need from the faculty and association in one place.',
      'home': 'Home',
      'einoWelcome': 'I’m Eino, the smart assistant inside the association app. Ask about study, the app, or general topics.',
      'einoHint': 'Message Eino...',
      'einoHomeSubtitle': 'A smart assistant for study, the association, and general questions.',
      'yourJourney': 'Your journey',
      'viewXp': 'XP details',
      'viewBadges': 'Badges',
      'levelReady': 'Level milestone reached 🎉',
      'levelReadySubtitle': 'You completed the current level target. Keep your study progress going.',
      'nextLevelGoal': 'Next milestone',
      'xpRemaining': '{value} XP remaining to the next level.',
      'einoGoalHome': 'Ask me about study or the app, and I’ll turn it into a practical next step.',
      'einoGoalMaterials': 'Let’s turn your current material into a simple study plan.',
      'einoGoalSchedule': 'Let’s organize your study day around your upcoming classes.',
      'einoGoalProgress': 'Let’s review your progress and choose the next useful step.',
      'einoGoalXp': 'Let’s turn your XP into a clear study goal.',
      'einoGoalBadges': 'Let’s find the closest badge you can earn without pressure.',
      'schedule': 'Schedule',
      'department': 'Department',
      'semester': 'Semester',
      'scheduleEmpty': 'No published classes are available for this selection.',
      'materials': 'Materials',
      'materialSearch': 'Search for a subject or file...',
      'more': 'More',
      'news': 'News',
      'media': 'Media',
      'mediaSubtitle': 'News, events, and activities in one place.',
      'events': 'Events',
      'reply': 'Reply',
      'writeReply': 'Write a reply',
      'commentReactionFailed': 'Could not react to the comment.',
      'networkOffline': 'No internet connection.',
      'serverError': 'There is a server error. Please try again.',
      'invalidServerResponse': 'Invalid server response.',
      'all': 'All',
      'officialNews': 'Official',
      'openNews': 'Open news details',
      'like': 'Like',
      'liked': 'Liked',
      'likeFailed': 'Could not register the like',
      'comments': 'Comments',
      'newsDetails': 'News details',
      'noComments': 'No comments yet.',
      'writeComment': 'Write a comment',
      'publish': 'Publish',
      'commentPublished': 'Comment published',
      'commentFailed': 'Could not publish the comment',
      'settingsSubtitle': 'Customize the interface, theme, and display options',
      'appearanceMode': 'Appearance mode',
      'checking': 'Checking…',
      'announcements': 'Announcements',
      'activities': 'Activities',
      'achievements': 'Achievements',
      'favorites': 'Favorites',
      'recent': 'Recently opened',
      'mostUsed': 'Most used',
      'downloads': 'Downloads',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Sign out',
      'logoutConfirm': 'Do you want to sign out of the student account?',
      'cancel': 'Cancel',
      'appInfo': 'App information',
      'about': 'About',
      'student': 'Student account',
      'studentOptional': 'Sign-in is optional, but required for study services.',
      'guest': 'Guest mode',
      'appearance': 'Appearance',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'latestNews': 'Latest news',
      'latestAnnouncement': 'Latest announcement',
      'continueLearning': 'Continue learning',
      'seeMore': 'See more',
      'connection': 'Service status',
      'connected': 'Connected',
      'connectionFailed': 'The service is currently unavailable',
      'checkConnection': 'Tap to check the connection',
      'noData': 'No data available right now.',
      'notReady': 'This service is not available yet.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'Offline',
      'error': 'Something went wrong',
      'refresh': 'Refresh',
      'lockedMaterials': 'Materials and schedule are available after student sign-in.',
      'quickAccess': 'Quick access',
      'allServices': 'All services',
      'yourStudy': 'Your study in one place',
      'explore': 'Explore',
      'latestUpdates': 'Latest updates',
      'publishedByAssociation': 'Published by the association',
      'viewAll': 'View all',
      'searchHint': 'Search materials, schedules and services...',
      'searchFilters': 'Search filters',
      'marketSearch': 'Search engineering tools...',
      'marketComingSoon': 'Engineering marketplace coming soon',
      'marketComingSoonSubtitle': 'The marketplace will be connected to real Dashboard data. We will not present demo listings as real listings.',
      'marketTrustNote': 'At launch, the marketplace will use trusted data and clear student policies.',
      'marketPlanTitle': 'How the marketplace will work',
      'marketPlanDashboard': 'Manage listings and content from the Dashboard',
      'marketPlanApi': 'Live synchronization between the API and the app',
      'marketPlanStudent': 'Protect publishing and interactions with student accounts',
      'studyProgress': 'Continue your study progress',
      'studyProgressSubtitle': 'Your specialty, materials and XP in one place.',
      'startStudy': 'Start your study experience',
      'startStudySubtitle': 'Sign in to access materials, schedule and progress.',
      'announcementsSubtitle': 'Important association alerts',
      'newsSubtitle': 'Latest faculty and association news',
      'activitiesSubtitle': 'New events and initiatives',
      'eino': 'Eino',
      'einoCardTitle': 'Your smart assistant inside TRINEX',
      'startChat': 'Start chat',
      'everythingYouNeed': 'Everything you need',
      'recentShort': 'Recent',
      'updateRequired': 'Update required',
      'updateAvailable': 'New update available',
      'installedVersion': 'Installed version: {version}',
      'availableVersion': 'Available version: {version}',
      'forceUpdateMessage': 'You must update the app to continue because this version is no longer supported.',
      'later': 'Later',
      'updateNow': 'Update now',
      'automatic': 'Automatic',
      'materialsLoadError': 'Could not load materials.\n{error}',
      'cannotOpenMaterial': 'Could not open the file. Check the link or your internet connection.',
      'materialOpenedExternally': 'The file was opened in the appropriate app on your device.',
      'progressNote': 'Update your progress while studying. Progress is saved to your account; opening a file alone does not grant XP.',
      'progressSaveError': 'Could not save your progress.',
      'subjectFallback': 'Subject',
      'fileCount': '{count} files',
      'noMaterialFiles': 'No files are available for this subject yet.',
      'noSubjects': 'No subjects are available for this semester and specialty yet.',
      'noPublishedFiles': 'Subjects exist, but no files have been published yet.',
      'updateCheckFailed': 'Could not check for updates right now.',
      'upToDate': 'You are using the latest available version.',
      'updateLinkMissing': 'Version {version} is available, but its update link is not configured.',
      'forceUpdateShort': 'This update is required to continue.',
      'versionLabel': 'Version {version}',
      'checkUpdates': 'Check for updates',
      'studentAccount': 'Student account',
      'studySpace': 'Your study space',
      'signInToStudy': 'Sign in to access materials, schedule, progress and badges.',
      'studentNumber': 'University number',
      'passwordOrCode': 'Password / verification code',
      'signIn': 'Sign in',
      'studentProfile': 'My student profile',
      'signOut': 'Sign out',
      'studentNumberValue': 'University number: {number}',
      'studentFallback': 'Student',
      'studyDashboard': 'Study dashboard',
      'xpLevel': 'XP & level',
      'level': 'Level',
      'xp': 'XP',
      'xpLog': 'XP history',
      'xpSubtitle': 'Points are awarded from verified study progress',
      'noXp': 'No XP yet. Start progressing through your study files.',
      'xpNextLevel': '{current} / {next} XP to next level',
      'xpEvent25': 'Complete 25% of a study file',
      'xpEvent50': 'Complete 50% of a study file',
      'xpEvent75': 'Complete 75% of a study file',
      'xpEventComplete': 'Complete a study file',
      'xpEventOther': 'Study activity',
      'achievementsTitle': 'Your achievements',
      'badgesEarned': '{earned} of {total} badges earned',
      'badgeCollection': 'Badge collection',
      'daySunday': 'Sunday',
      'dayMonday': 'Monday',
      'dayTuesday': 'Tuesday',
      'dayWednesday': 'Wednesday',
      'dayThursday': 'Thursday',
      'dayFriday': 'Friday',
      'daySaturday': 'Saturday',
      'dayUnknown': 'Day {day}',
      'materialsStudentSubtitle': 'Materials for your department and linked semester',
      'scheduleStudentSubtitle': 'Your department and current semester schedule',
      'progressStudentSubtitle': 'Track your progress through files',
      'badgesStudentSubtitle': 'Your study achievements',
      'xpLoadError': 'Could not load XP.',
      'badgesLoadError': 'Could not load badges.',
'einoMemoryAdd': 'Add memory',
      'einoMemoryAddHint': 'Example: I prefer explanations with engineering examples.',
      'einoMemoryCategory': 'Category',
'einoMemoryTitle': 'Eino memory',
      'einoMemorySubtitle': 'Saved memories Eino can use when relevant.',
      'einoMemoryEmpty': 'No saved memories yet.',
      'einoMemoryForget': 'Forget memory',
      'einoOnlineReady': 'Eino is connected to cloud AI',
      'einoOfflineMode': 'Eino is offline',
      'einoOfflineReady': 'A local engine is available on this device.',
      'einoModel': 'Model',
      'einoModelIntegrityFailed': 'The local model file is invalid or changed. Download it again.',
      'einoModelBenchmark': 'Benchmark model',
      'einoModelBenchmarkResult': 'Approx. speed: {speed} tok/s — first token: {first} ms',
      'einoCheckingCapabilities': 'Checking Eino capabilities…',
      'einoTitle': 'Eino',
      'newChat': 'New chat',
      'einoHistory': 'Eino chats',
      'einoOnline': 'Online now',
      'einoAttach': 'Attach',
      'einoAttachImage': 'Image',
      'einoVisionSubtitle': 'Analyze an image with Eino',
      'einoAttachDocument': 'Document',
      'einoDocumentSubtitle': 'PDF, DOCX or TXT',
      'einoVoice': 'Voice input',
      'einoStopRecording': 'Stop recording',
      'einoMicPermission': 'Allow microphone access to record audio.',
      'einoProcessing': 'Processing…',
      'einoListen': 'Listen to response',
      'einoNoHistory': 'No previous chats yet.',
      'send': 'Send',
      'copy': 'Copy',
      'copied': 'Copied',
      'einoGreeting': 'I’m Eino ✨',
      'withYou': 'I’m with you in {section}',
      'suggestions': 'Suggestions for you',
      'sourceHome': 'Home',
      'sourceMaterials': 'Study materials',
      'sourceSchedule': 'Schedule',
      'sourceProgress': 'Study progress',
      'sourceXp': 'XP',
      'sourceBadges': 'Badges',
      'sourceStudent': 'Student account',
      'suggestStudyPlan': 'Help me plan my study',
      'suggestExplainMaterial': 'Explain a concept from my material',
      'suggestStartFile': 'How should I start this file?',
      'suggestOrganizeDay': 'Organize my study day',
      'suggestPrepareClass': 'How should I prepare for my next class?',
      'suggestReviewTime': 'Suggest a review time',
      'suggestImproveProgress': 'How can I improve my progress?',
      'suggestReviewPlan': 'Help me make a review plan',
      'suggestKeepGoing': 'How can I keep going without pressure?',
      'suggestEarnXp': 'How do I earn XP from studying?',
      'suggestProgressMethod': 'What is a good way to progress?',
      'suggestStudyGoal': 'Help me set a study goal',
      'suggestBadges': 'How do I earn badges?',
      'suggestNearbyGoal': 'Suggest a nearby goal',
      'suggestKeepProgress': 'How do I maintain my progress?',
      'suggestStudy': '📚 Help me study',
      'suggestDay': '🗓️ Help me plan my day',
      'suggestConcept': '💡 Explain a concept',
      'suggestApp': '🔎 Help me use the app',
      'progressLoadError': 'Could not load your study progress.',
      'progressSummary': 'Progress summary',
      'progressRealActivity': 'Your progress is based on real study activity',
      'filesStarted': 'Files started',
      'filesCompleted': 'Completed',
      'activeMinutes': 'Active minutes',
      'recentFiles': 'Your recent files',
      'noProgress': 'No progress recorded yet. Start from study materials.',
      'studyFile': 'Study file',
      'completed': 'Completed',
      'inProgress': 'In progress',
      'badgesTitle': 'Badges',
      'semesterFallback': 'Semester {number}',
      'sessionInitializing': 'Initializing the student session.',
      'retry': 'Retry',
      'studentServices': 'Study services',
      'studentServicesLockedTitle': 'Sign in to access your study services',
      'studentServicesLockedSubtitle': 'Materials, schedule, progress and badges are linked to your student account.',
      'xpValue': '{value} XP',
      'levelValue': 'Level {level}',
      'notificationsCenter': 'Notifications center',
      'unreadCount': '{count} unread notifications',
      'allNotifications': 'All',
      'unreadNotifications': 'Unread',
      'noUnreadNotifications': 'There are no unread notifications.',
      'onboardingTitle1': 'Integrated Academic Platform',
      'onboardingDesc1': 'Lectures, summaries, and references organized by engineering major and current semester.',
      'onboardingSubtitle1': 'Lectures, summaries, and references organized by engineering major and current semester.',
      'onboardingTitle2': 'Eino — Your Smart Assistant',
      'onboardingDesc2': 'An interactive character answering questions, organizing your schedule, and clarifying engineering concepts.',
      'onboardingSubtitle2': 'An interactive character answering questions, organizing your schedule, and clarifying engineering concepts.',
      'onboardingTitle3': 'Engineering Community',
      'onboardingDesc3': 'Stay updated with official college news, association events, and engineering utilities.',
      'onboardingSubtitle3': 'Stay updated with official college news, association events, and engineering utilities.',
      'createAccount': 'Create Account',
      'continueAsGuest': 'Continue as Guest',
      'skip': 'Skip',
      'next': 'Next',
      'startNow': 'Get Started',
      'getStarted': 'Get Started',
      'guestNoticeTitle': 'Guest Browsing Notice',
      'guestNoticeDesc': 'Browsing as a guest lets you explore news, activities, engineering tools, and chat with Eino. Enrolled courses and schedules require a student account.',
      'understood': 'Understood',
      'registerTitle': 'New Student Registration',
      'registerSubtitle': 'Create your academic account to access courses and class schedules.',
      'academicId': 'University ID',
      'academicIdHint': 'e.g. 20210045',
      'academicIdHelp': 'ID registered with the College of Engineering & Architecture.',
      'selectDepartment': 'Academic Major',
      'departmentLockedHelp': 'Major is fixed after registration and cannot be changed without association approval.',
      'selectSemester': 'Academic Semester',
      'semesterFlexibleHelp': 'You can easily update your semester later from Settings.',
      'email': 'Email Address',
      'emailHint': 'student@domain.edu',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'passwordMismatch': 'Passwords do not match.',
      'passwordTooShort': 'Password must be at least 8 characters.',
      'alreadyHaveAccount': 'Already have an account?',
      'dontHaveAccount': 'New student?',
      'accentColor': 'Accent Color',
      'replayOnboarding': 'View Introduction Screens (Onboarding)',
      'updateSemesterTitle': 'Update Current Semester',
      'semesterUpdatedSuccess': 'Your semester was updated successfully.',
      'changeSemester': 'Change Semester',
      'studentLockedCardTitle': 'Enrolled Academic Content',
      'studentLockedCardDesc': 'Sign in or register to browse your major’s curriculum and schedule.',
      'unitConverter': 'Unit Converter',
      'gpaCalculator': 'GPA Calculator',
      'resistorCalculator': 'Resistor Color Decoder',
      'engineeringReferences': 'Formulas & References',
      'unitConverterTitle': 'Unit Converter',
      'gpaCalculatorTitle': 'GPA Calculator',
      'resistorDecoderTitle': 'Resistor Color Decoder',
      'engineeringRefsTitle': 'Formulas & References',
      'toolsTitle': 'Engineering Tools',
      'toolsSubtitle': 'Practical engineering utilities for students.',
      'value': 'Value',
      'from': 'From',
      'to': 'To',
      'result': 'Result',
      'calculate': 'Calculate',
      'courses': 'Courses',
      'grade': 'Grade',
      'credits': 'Credits',
      'gpaResult': 'Calculated GPA: {gpa}',
      'todaySchedule': 'Today\'s Schedule',
      'noClassesToday': 'No classes scheduled for today.',
      'viewFullSchedule': 'View Full Schedule',
      'myMaterials': 'My Courses',
      'quickPromptEino': 'Ask Eino anything...',
      'guestWelcomeTitle': 'Welcome to TRINEX',
      'guestWelcomeSubtitle': 'Official student platform for the College of Engineering & Architecture',
      'guestBannerNotice': 'You are browsing as a guest. Sign in to access your course materials and schedules.',
    },
    'fr': {
      'einoProviderBusy': 'Le fournisseur IA est occupé. Attendez un instant puis réessayez.',
      'einoProviderUnavailable': 'Le fournisseur d’Eino est indisponible pour le moment. Réessayez bientôt.',
      'einoProviderRoute': 'Le routage d’Eino est indisponible pour le moment. Réessayez plus tard.',
      'einoProviderAuth': 'Eino n’a pas pu vérifier sa connexion au fournisseur. Réessayez plus tard.',
      'einoTimeout': 'La réponse prend plus de temps que prévu. Réessayez.',
      'einoRateLimited': 'L’utilisation est temporairement limitée. Attendez un instant puis réessayez.',
      'einoGenericError': 'Une erreur est survenue lors de la connexion à Eino. Réessayez.',
      'einoRetry': 'Réessayer',
      'loginFieldsRequired': 'Saisissez votre numéro étudiant et votre mot de passe.',
      'loginFailed': 'La connexion a échoué. Vérifiez vos informations et réessayez.',
      'appName': 'TRINEX',
      'splashTagline': 'Tout ce dont vous avez besoin, au même endroit.',
      'welcome': 'Bienvenue sur TRINEX 👋',
      'welcomeBack': 'Bon retour 👋',
      'studySpaceReady': 'Votre espace d’étude est prêt.',
      'lecturesFiles': 'Cours et fichiers',
      'upcomingClasses': 'Cours à venir',
      'latestAlerts': 'Dernières alertes',
      'market': 'Boutique',
      'engineeringTools': 'Outils d’ingénierie',
      'homeSubtitle': 'Tout ce qui concerne la faculté et l’association au même endroit.',
      'home': 'Accueil',
      'einoWelcome': 'Je suis Eino, l’assistant intelligent de l’application. Posez vos questions sur les études, l’association ou des sujets généraux.',
      'einoHint': 'Écrivez à Eino...',
      'einoHomeSubtitle': 'Un assistant intelligent pour les études, l’association et les questions générales.',
      'yourJourney': 'Votre parcours',
      'viewXp': 'Détails XP',
      'viewBadges': 'Badges',
      'levelReady': 'Niveau atteint 🎉',
      'levelReadySubtitle': 'Vous avez atteint l’objectif du niveau actuel. Continuez votre progression.',
      'nextLevelGoal': 'Prochain objectif',
      'xpRemaining': 'Encore {value} XP pour le niveau suivant.',
      'einoGoalHome': 'Posez-moi une question sur les études ou l’application pour obtenir une prochaine étape concrète.',
      'einoGoalMaterials': 'Transformons votre cours actuel en plan d’étude simple.',
      'einoGoalSchedule': 'Organisons votre journée autour de vos prochains cours.',
      'einoGoalProgress': 'Examinons votre progression et choisissons la prochaine étape utile.',
      'einoGoalXp': 'Transformons vos XP en objectif d’étude clair.',
      'einoGoalBadges': 'Cherchons le badge le plus proche, sans pression.',
      'schedule': 'Emploi du temps',
      'department': 'Département',
      'semester': 'Semestre',
      'scheduleEmpty': 'Aucun cours publié pour cette sélection.',
      'materials': 'Supports',
      'materialSearch': 'Rechercher une matière ou un fichier...',
      'more': 'Plus',
      'news': 'Actualités',
      'media': 'Médias',
      'mediaSubtitle': 'Actualités, événements et activités au même endroit.',
      'events': 'Événements',
      'reply': 'Répondre',
      'writeReply': 'Écrire une réponse',
      'commentReactionFailed': 'Impossible de réagir au commentaire.',
      'networkOffline': 'Aucune connexion Internet.',
      'serverError': 'Une erreur du serveur est survenue. Réessayez.',
      'invalidServerResponse': 'Réponse du serveur invalide.',
      'all': 'Toutes',
      'officialNews': 'Officiel',
      'openNews': 'Ouvrir les détails',
      'like': 'J’aime',
      'liked': 'Aimé',
      'likeFailed': 'Impossible d’enregistrer le J’aime',
      'comments': 'Commentaires',
      'newsDetails': 'Détails de l’actualité',
      'noComments': 'Aucun commentaire pour le moment.',
      'writeComment': 'Écrire un commentaire',
      'publish': 'Publier',
      'commentPublished': 'Commentaire publié',
      'commentFailed': 'Impossible de publier le commentaire',
      'settingsSubtitle': 'Personnalisez l’interface, le thème et l’affichage',
      'appearanceMode': 'Mode d’affichage',
      'checking': 'Vérification…',
      'announcements': 'Annonces',
      'activities': 'Activités',
      'achievements': 'Réalisations',
      'favorites': 'Favoris',
      'recent': 'Récemment ouverts',
      'mostUsed': 'Les plus utilisés',
      'downloads': 'Téléchargements',
      'notifications': 'Notifications',
      'settings': 'Paramètres',
      'logout': 'Se déconnecter',
      'logoutConfirm': 'Voulez-vous vous déconnecter du compte étudiant ?',
      'cancel': 'Annuler',
      'appInfo': 'Informations de l’application',
      'about': 'À propos',
      'student': 'Compte étudiant',
      'studentOptional': 'La connexion est facultative, mais requise pour les services d’étude.',
      'guest': 'Mode invité',
      'appearance': 'Apparence',
      'language': 'Langue',
      'system': 'Système',
      'light': 'Clair',
      'dark': 'Sombre',
      'latestNews': 'Dernières actualités',
      'latestAnnouncement': 'Dernière annonce',
      'continueLearning': 'Continuer l’apprentissage',
      'seeMore': 'Voir plus',
      'connection': 'État du service',
      'connected': 'Connecté',
      'connectionFailed': 'Service actuellement indisponible',
      'checkConnection': 'Touchez pour vérifier la connexion',
      'noData': 'Aucune donnée disponible pour le moment.',
      'notReady': 'Ce service n’est pas encore disponible.',
      'arabic': 'العربية',
      'english': 'English',
      'french': 'Français',
      'offline': 'Hors ligne',
      'error': 'Une erreur est survenue',
      'refresh': 'Actualiser',
      'lockedMaterials': 'Les supports et l’emploi du temps sont disponibles après connexion.',
      'quickAccess': 'Accès rapide',
      'allServices': 'Tous les services',
      'yourStudy': 'Vos études au même endroit',
      'explore': 'Explorer',
      'latestUpdates': 'Dernières mises à jour',
      'publishedByAssociation': 'Publié par l’association',
      'viewAll': 'Tout voir',
      'searchHint': 'Rechercher des supports, horaires et services...',
      'searchFilters': 'Filtres de recherche',
      'marketSearch': 'Rechercher des outils d’ingénierie...',
      'marketComingSoon': 'La boutique d’outils d’ingénierie arrive bientôt',
      'marketComingSoonSubtitle': 'La boutique sera connectée aux vraies données du Dashboard. Aucun contenu de démonstration ne sera présenté comme réel.',
      'marketTrustNote': 'Au lancement, la boutique utilisera des données fiables et des règles étudiantes claires.',
      'marketPlanTitle': 'Fonctionnement prévu',
      'marketPlanDashboard': 'Gérer les annonces et le contenu depuis le Dashboard',
      'marketPlanApi': 'Synchronisation en direct entre l’API et l’application',
      'marketPlanStudent': 'Protéger la publication et les interactions par le compte étudiant',
      'studyProgress': 'Continuer vos études',
      'studyProgressSubtitle': 'Votre spécialité, vos supports et vos XP au même endroit.',
      'startStudy': 'Commencer votre expérience',
      'startStudySubtitle': 'Connectez-vous pour accéder aux supports, horaires et progrès.',
      'announcementsSubtitle': 'Alertes importantes de l’association',
      'newsSubtitle': 'Dernières nouvelles de la faculté et de l’association',
      'activitiesSubtitle': 'Nouveaux événements et initiatives',
      'eino': 'Eino',
      'einoCardTitle': 'Votre assistant intelligent dans TRINEX',
      'startChat': 'Démarrer la conversation',
      'everythingYouNeed': 'Tout ce dont vous avez besoin',
      'recentShort': 'Récents',
      'updateRequired': 'Mise à jour requise',
      'updateAvailable': 'Nouvelle mise à jour disponible',
      'installedVersion': 'Version installée : {version}',
      'availableVersion': 'Version disponible : {version}',
      'forceUpdateMessage': 'Vous devez mettre à jour l’application pour continuer, car cette version n’est plus prise en charge.',
      'later': 'Plus tard',
      'updateNow': 'Mettre à jour',
      'automatic': 'Automatique',
      'materialsLoadError': 'Impossible de charger les supports.\n{error}',
      'cannotOpenMaterial': 'Impossible d’ouvrir le fichier. Vérifiez le lien ou votre connexion Internet.',
      'materialOpenedExternally': 'Le fichier a été ouvert dans l’application appropriée sur votre appareil.',
      'progressNote': 'Mettez à jour votre progression pendant vos études. La progression est enregistrée sur votre compte ; ouvrir un fichier seul ne donne pas de XP.',
      'progressSaveError': 'Impossible d’enregistrer la progression.',
      'subjectFallback': 'Matière',
      'fileCount': '{count} fichiers',
      'noMaterialFiles': 'Aucun fichier n’est disponible pour cette matière pour le moment.',
      'noSubjects': 'Aucune matière n’est disponible pour ce semestre et cette spécialité.',
      'noPublishedFiles': 'Les matières existent, mais aucun fichier n’a encore été publié.',
      'updateCheckFailed': 'Impossible de vérifier les mises à jour pour le moment.',
      'upToDate': 'Vous utilisez la dernière version disponible.',
      'updateLinkMissing': 'La version {version} est disponible, mais son lien de mise à jour n’est pas configuré.',
      'forceUpdateShort': 'Cette mise à jour est requise pour continuer.',
      'versionLabel': 'Version {version}',
      'checkUpdates': 'Vérifier les mises à jour',
      'studentAccount': 'Compte étudiant',
      'studySpace': 'Votre espace d’étude',
      'signInToStudy': 'Connectez-vous pour accéder aux supports, horaires, progrès et badges.',
      'studentNumber': 'Numéro universitaire',
      'passwordOrCode': 'Mot de passe / code de vérification',
      'signIn': 'Se connecter',
      'studentProfile': 'Mon profil étudiant',
      'signOut': 'Se déconnecter',
      'studentNumberValue': 'Numéro universitaire : {number}',
      'studentFallback': 'Étudiant',
      'studyDashboard': 'Tableau de bord étudiant',
      'xpLevel': 'XP et niveau',
      'level': 'Niveau',
      'xp': 'XP',
      'xpLog': 'Historique XP',
      'xpSubtitle': 'Les points sont attribués à partir d’une progression d’étude vérifiée',
      'noXp': 'Pas encore de XP. Commencez votre progression dans vos fichiers d’étude.',
      'xpNextLevel': '{current} / {next} XP pour le niveau suivant',
      'xpEvent25': 'Terminer 25 % d’un fichier d’étude',
      'xpEvent50': 'Terminer 50 % d’un fichier d’étude',
      'xpEvent75': 'Terminer 75 % d’un fichier d’étude',
      'xpEventComplete': 'Terminer un fichier d’étude',
      'xpEventOther': 'Activité d’étude',
      'achievementsTitle': 'Vos réalisations',
      'badgesEarned': '{earned} sur {total} badges obtenus',
      'badgeCollection': 'Collection de badges',
      'daySunday': 'Dimanche',
      'dayMonday': 'Lundi',
      'dayTuesday': 'Mardi',
      'dayWednesday': 'Mercredi',
      'dayThursday': 'Jeudi',
      'dayFriday': 'Vendredi',
      'daySaturday': 'Samedi',
      'dayUnknown': 'Jour {day}',
      'materialsStudentSubtitle': 'Supports de votre département et semestre associé',
      'scheduleStudentSubtitle': 'Emploi du temps de votre département et semestre actuel',
      'progressStudentSubtitle': 'Suivez votre progression dans les fichiers',
      'badgesStudentSubtitle': 'Vos réalisations d’étude',
      'xpLoadError': 'Impossible de charger les XP.',
      'badgesLoadError': 'Impossible de charger les badges.',
'einoMemoryAdd': 'Ajouter un souvenir',
      'einoMemoryAddHint': 'Exemple : je préfère les explications avec des exemples d’ingénierie.',
      'einoMemoryCategory': 'Catégorie',
'einoMemoryTitle': 'Mémoire Eino',
      'einoMemorySubtitle': 'Souvenirs enregistrés que Eino peut utiliser lorsqu’ils sont pertinents.',
      'einoMemoryEmpty': 'Aucun souvenir enregistré.',
      'einoMemoryForget': 'Oublier',
      'einoOnlineReady': 'Eino est connectée à l’IA cloud',
      'einoOfflineMode': 'Eino est hors ligne',
      'einoOfflineReady': 'Un moteur local est disponible sur cet appareil.',
      'einoModel': 'Modèle',
      'einoModelIntegrityFailed': 'Le fichier du modèle local est invalide ou a changé. Téléchargez-le à nouveau.',
      'einoModelBenchmark': 'Tester le modèle',
      'einoModelBenchmarkResult': 'Vitesse approx. : {speed} tok/s — premier token : {first} ms',
      'einoCheckingCapabilities': 'Vérification des capacités d’Eino…',
      'einoTitle': 'Eino',
      'newChat': 'Nouvelle conversation',
      'einoHistory': 'Conversations Eino',
      'einoOnline': 'En ligne',
      'einoAttach': 'Joindre',
      'einoAttachImage': 'Image',
      'einoVisionSubtitle': 'Analyser une image avec Eino',
      'einoAttachDocument': 'Document',
      'einoDocumentSubtitle': 'PDF, DOCX ou TXT',
      'einoVoice': 'Entrée vocale',
      'einoStopRecording': 'Arrêter l’enregistrement',
      'einoMicPermission': 'Autorisez le microphone pour enregistrer.',
      'einoProcessing': 'Traitement…',
      'einoListen': 'Écouter la réponse',
      'einoNoHistory': 'Aucune conversation précédente.',
      'send': 'Envoyer',
      'copy': 'Copier',
      'copied': 'Copié',
      'einoGreeting': 'Je suis Eino ✨',
      'withYou': 'Je suis avec vous dans {section}',
      'suggestions': 'Suggestions pour vous',
      'sourceHome': 'Accueil',
      'sourceMaterials': 'Supports d’étude',
      'sourceSchedule': 'Emploi du temps',
      'sourceProgress': 'Progression',
      'sourceXp': 'XP',
      'sourceBadges': 'Badges',
      'sourceStudent': 'Compte étudiant',
      'suggestStudyPlan': 'Aidez-moi à organiser mes études',
      'suggestExplainMaterial': 'Expliquez un concept de mon cours',
      'suggestStartFile': 'Comment commencer ce fichier ?',
      'suggestOrganizeDay': 'Organisez ma journée d’étude',
      'suggestPrepareClass': 'Comment préparer mon prochain cours ?',
      'suggestReviewTime': 'Proposez un moment de révision',
      'suggestImproveProgress': 'Comment améliorer ma progression ?',
      'suggestReviewPlan': 'Aidez-moi à créer un plan de révision',
      'suggestKeepGoing': 'Comment continuer sans pression ?',
      'suggestEarnXp': 'Comment gagner des XP en étudiant ?',
      'suggestProgressMethod': 'Quelle bonne méthode pour progresser ?',
      'suggestStudyGoal': 'Aidez-moi à fixer un objectif d’étude',
      'suggestBadges': 'Comment obtenir des badges ?',
      'suggestNearbyGoal': 'Proposez-moi un objectif proche',
      'suggestKeepProgress': 'Comment maintenir ma progression ?',
      'suggestStudy': '📚 Aidez-moi à étudier',
      'suggestDay': '🗓️ Aidez-moi à organiser ma journée',
      'suggestConcept': '💡 Expliquez un concept',
      'suggestApp': '🔎 Aidez-moi avec l’application',
      'progressLoadError': 'Impossible de charger votre progression.',
      'progressSummary': 'Résumé de la progression',
      'progressRealActivity': 'Votre progression repose sur une activité d’étude réelle',
      'filesStarted': 'Fichiers commencés',
      'filesCompleted': 'Terminés',
      'activeMinutes': 'Minutes actives',
      'recentFiles': 'Vos fichiers récents',
      'noProgress': 'Aucune progression enregistrée. Commencez par les supports d’étude.',
      'studyFile': 'Fichier d’étude',
      'completed': 'Terminé',
      'inProgress': 'En cours',
      'badgesTitle': 'Badges',
      'semesterFallback': 'Semestre {number}',
      'sessionInitializing': 'Initialisation de la session étudiante.',
      'retry': 'Réessayer',
      'studentServices': 'Services d’étude',
      'studentServicesLockedTitle': 'Connectez-vous pour accéder à vos services d’étude',
      'studentServicesLockedSubtitle': 'Les supports, l’emploi du temps, la progression et les badges sont liés à votre compte étudiant.',
      'xpValue': '{value} XP',
      'levelValue': 'Niveau {level}',
      'notificationsCenter': 'Centre des notifications',
      'unreadCount': '{count} notifications non lues',
      'allNotifications': 'Toutes',
      'unreadNotifications': 'Non lues',
      'noUnreadNotifications': 'Aucune notification non lue.',
      'onboardingTitle1': 'Plateforme Académique Intégrée',
      'onboardingDesc1': 'Cours, résumés et références organisés par filière d’ingénierie et semestre en cours.',
      'onboardingSubtitle1': 'Cours, résumés et références organisés par filière d’ingénierie et semestre en cours.',
      'onboardingTitle2': 'Eino — Votre Assistante Intelligente',
      'onboardingDesc2': 'Un personnage interactif répondant à vos questions et clarifiant vos cours d’ingénierie.',
      'onboardingSubtitle2': 'Un personnage interactif répondant à vos questions et clarifiant vos cours d’ingénierie.',
      'onboardingTitle3': 'Communauté de la Faculté',
      'onboardingDesc3': 'Suivez les actualités officielles, les activités associatives et les outils pratiques.',
      'onboardingSubtitle3': 'Suivez les actualités officielles, les activités associatives et les outils pratiques.',
      'createAccount': 'Créer un compte',
      'continueAsGuest': 'Continuer en tant qu’invité',
      'skip': 'Passer',
      'next': 'Suivant',
      'startNow': 'Commencer',
      'getStarted': 'Commencer',
      'guestNoticeTitle': 'Navigation en mode invité',
      'guestNoticeDesc': 'Le mode invité permet de consulter les actualités, les outils et discuter avec Eino. Les cours et plannings nécessitent un compte étudiant.',
      'understood': 'J’ai compris',
      'registerTitle': 'Inscription Étudiant',
      'registerSubtitle': 'Créez votre compte académique pour accéder à vos cours et plannings.',
      'academicId': 'Numéro Étudiant',
      'academicIdHint': 'ex: 20210045',
      'academicIdHelp': 'Numéro inscrit au registre de la Faculté de Génie et Architecture.',
      'selectDepartment': 'Filière Académique',
      'departmentLockedHelp': 'La filière est fixée après inscription et ne peut être modifiée qu’auprès de l’association.',
      'selectSemester': 'Semestre Académique',
      'semesterFlexibleHelp': 'Vous pourrez modifier votre semestre dans les paramètres.',
      'email': 'Adresse E-mail',
      'emailHint': 'etudiant@domaine.edu',
      'password': 'Mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'passwordMismatch': 'Les mots de passe ne correspondent pas.',
      'passwordTooShort': 'Le mot de passe doit comporter au moins 8 caractères.',
      'alreadyHaveAccount': 'Déjà un compte ?',
      'dontHaveAccount': 'Nouvel étudiant ?',
      'accentColor': 'Couleur d’accentuation',
      'replayOnboarding': 'Revoir la présentation (Onboarding)',
      'updateSemesterTitle': 'Modifier le semestre actuel',
      'semesterUpdatedSuccess': 'Votre semestre a été mis à jour avec succès.',
      'changeSemester': 'Changer de semestre',
      'studentLockedCardTitle': 'Contenu réservé aux étudiants',
      'studentLockedCardDesc': 'Connectez-vous pour consulter le programme et l’emploi du temps de votre filière.',
      'unitConverter': 'Convertisseur d’unités',
      'gpaCalculator': 'Calculateur de moyenne',
      'resistorCalculator': 'Décodeur de résistances',
      'engineeringReferences': 'Formules et Références',
      'unitConverterTitle': 'Convertisseur d’unités',
      'gpaCalculatorTitle': 'Calculateur de moyenne',
      'resistorDecoderTitle': 'Décodeur de résistances',
      'engineeringRefsTitle': 'Formules et Références',
      'toolsTitle': 'Outils d’Ingénierie',
      'toolsSubtitle': 'Utilitaires pratiques pour étudiants en ingénierie.',
      'value': 'Valeur',
      'from': 'De',
      'to': 'À',
      'result': 'Résultat',
      'calculate': 'Calculer',
      'courses': 'Cours',
      'grade': 'Note',
      'credits': 'Crédits',
      'gpaResult': 'Moyenne calculée : {gpa}',
      'todaySchedule': 'Emploi du temps d’aujourd’hui',
      'noClassesToday': 'Aucun cours programmé aujourd’hui.',
      'viewFullSchedule': 'Voir tout l’emploi du temps',
      'myMaterials': 'Mes Cours',
      'quickPromptEino': 'Posez une question à Eino...',
      'guestWelcomeTitle': 'Bienvenue sur TRINEX',
      'guestWelcomeSubtitle': 'Plateforme officielle des étudiants de la Faculté de Génie et Architecture',
      'guestBannerNotice': 'Vous naviguez en mode invité. Connectez-vous pour accéder à vos cours et emplois du temps.',
    },
  };

  String t(String key, [Map<String, String>? params]) {
    var value = _values[locale.languageCode]?[key] ?? _values['ar']![key] ?? key;
    if (params != null) {
      for (final entry in params.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales
          .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
