-- Immutable badge catalogue. Badge definitions are application-owned and not dashboard-managed.
INSERT OR IGNORE INTO badges (id,name_ar,description_ar,icon_url,rule_type,rule_value,active,sort_order) VALUES
('badge-first-step','البداية','ابدأ أول تقدم دراسي موثق.',NULL,'progress_events',1,1,10),
('badge-five-progress','خطوة ثابتة','سجّل 5 عمليات تقدم دراسي.',NULL,'progress_events',5,1,20),
('badge-ten-progress','مواظب','سجّل 10 عمليات تقدم دراسي.',NULL,'progress_events',10,1,30),
('badge-twentyfive-progress','متابع قوي','سجّل 25 عملية تقدم دراسي.',NULL,'progress_events',25,1,40),
('badge-fifty-progress','لا تتوقف','سجّل 50 عملية تقدم دراسي.',NULL,'progress_events',50,1,50),
('badge-hundred-progress','مئة خطوة','سجّل 100 عملية تقدم دراسي.',NULL,'progress_events',100,1,60),
('badge-quarter-thousand-progress','ربع ألف','سجّل 250 عملية تقدم دراسي.',NULL,'progress_events',250,1,70),
('badge-first-complete','أول إنجاز','أكمل أول ملف دراسي.',NULL,'completed_materials',1,1,100),
('badge-three-complete','ثلاثة ملفات','أكمل 3 ملفات دراسية.',NULL,'completed_materials',3,1,110),
('badge-five-complete','خمسة ملفات','أكمل 5 ملفات دراسية.',NULL,'completed_materials',5,1,120),
('badge-ten-complete','عشرة ملفات','أكمل 10 ملفات دراسية.',NULL,'completed_materials',10,1,130),
('badge-twenty-complete','عشرون ملفًا','أكمل 20 ملفًا دراسيًا.',NULL,'completed_materials',20,1,140),
('badge-thirty-complete','ثلاثون ملفًا','أكمل 30 ملفًا دراسيًا.',NULL,'completed_materials',30,1,150),
('badge-fifty-complete','موسوعة','أكمل 50 ملفًا دراسيًا.',NULL,'completed_materials',50,1,160),
('badge-first-subject','أول مادة','أكمل مادة دراسية واحدة.',NULL,'completed_subjects',1,1,200),
('badge-three-subjects','متعدد المواد','أكمل مواد من 3 مقررات مختلفة.',NULL,'completed_subjects',3,1,210),
('badge-five-subjects','واسع المعرفة','أكمل مواد من 5 مقررات مختلفة.',NULL,'completed_subjects',5,1,220),
('badge-eight-subjects','جامع المقررات','أكمل مواد من 8 مقررات مختلفة.',NULL,'completed_subjects',8,1,230),
('badge-xp-50','أول دفعة','اجمع 50 XP.',NULL,'xp_total',50,1,300),
('badge-xp-100','مئة XP','اجمع 100 XP.',NULL,'xp_total',100,1,310),
('badge-xp-250','ربع ألف XP','اجمع 250 XP.',NULL,'xp_total',250,1,320),
('badge-xp-500','500 XP','اجمع 500 XP.',NULL,'xp_total',500,1,330),
('badge-xp-1000','1000 XP','اجمع 1000 XP.',NULL,'xp_total',1000,1,340),
('badge-xp-2000','2000 XP','اجمع 2000 XP.',NULL,'xp_total',2000,1,350),
('badge-xp-5000','5000 XP','اجمع 5000 XP.',NULL,'xp_total',5000,1,360),
('badge-level-2','المستوى 2','وصل إلى المستوى الثاني.',NULL,'level',2,1,400),
('badge-level-3','المستوى 3','وصل إلى المستوى الثالث.',NULL,'level',3,1,410),
('badge-level-5','المستوى 5','وصل إلى المستوى الخامس.',NULL,'level',5,1,420),
('badge-level-10','المستوى 10','وصل إلى المستوى العاشر.',NULL,'level',10,1,430),
('badge-level-15','المستوى 15','وصل إلى المستوى الخامس عشر.',NULL,'level',15,1,440),
('badge-first-event','أول حدث','أكمل أول حدث تعليمي.',NULL,'learning_events',1,1,500),
('badge-five-events','محب التعلم','أكمل 5 أحداث تعليمية.',NULL,'learning_events',5,1,510),
('badge-ten-events','صانع العادة','أكمل 10 أحداث تعليمية.',NULL,'learning_events',10,1,520),
('badge-first-comment','صوتك مهم','اكتب أول تعليق ظاهر.',NULL,'comments',1,1,600),
('badge-five-comments','مشارك','اكتب 5 تعليقات ظاهرة.',NULL,'comments',5,1,610),
('badge-ten-comments','حوار مستمر','اكتب 10 تعليقات ظاهرة.',NULL,'comments',10,1,620),
('badge-first-reaction','تفاعل أول','أضف أول تفاعل.',NULL,'reactions',1,1,630),
('badge-ten-reactions','متفاعل','أضف 10 تفاعلات.',NULL,'reactions',10,1,640),
('badge-first-reply','مجيب','اكتب أول رد على تعليق.',NULL,'replies',1,1,650),
('badge-five-replies','حوار بنّاء','اكتب 5 ردود على التعليقات.',NULL,'replies',5,1,660);
