import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../core/constants/app_constants.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/auth_storage.dart';
import '../../data/models/student_profile.dart';
import '../../data/repositories/student_repository.dart';
import '../../core/theme/design_tokens.dart';

class StudentScreen extends StatefulWidget{const StudentScreen({super.key});@override State<StudentScreen> createState()=>_StudentScreenState();}
class _StudentScreenState extends State<StudentScreen>{final _id=TextEditingController();final _password=TextEditingController();AuthStorage? _storage;ApiClient? _client;StudentRepository? _repo;StudentProfile? _profile;Map<String,dynamic> _stats={};bool _loading=true;String? _error;@override void initState(){super.initState();_init();}@override void dispose(){_id.dispose();_password.dispose();_client?.dispose();super.dispose();}Future<void> _init()async{final prefs=await SharedPreferences.getInstance();_storage=AuthStorage(prefs);_client=ApiClient(baseUrl:AppConstants.apiBaseUrl,authStorage:_storage);_repo=StudentRepository(_client!);if(_storage!.isLoggedIn)await _load();if(mounted)setState(()=>_loading=false);}Future<void> _load()async{try{final r=_repo;if(r==null)return;final p=await r.profile();final s=await r.stats();if(mounted)setState((){_profile=p;_stats=s;_error=null;});}catch(e){if(mounted)setState(()=>_error=e.toString());}}Future<void> _login()async{if(_client==null||_storage==null||_id.text.trim().isEmpty||_password.text.isEmpty)return;setState(()=>_loading=true);try{final json=await _client!.postJson('/api/v1/auth/login',body:{'studentNumber':_id.text.trim(),'password':_password.text});final data=json['data'];if(data is Map)await _storage!.saveSession(Map<String,dynamic>.from(data));await _load();}catch(e){if(mounted)setState(()=>_error=e.toString());}finally{if(mounted)setState(()=>_loading=false);}}Future<void> _logout()async{try{await _client?.postJson('/api/v1/auth/logout');}catch(_){ }await _storage?.clear();if(mounted)setState((){_profile=null;_stats={};});}
@override Widget build(BuildContext context)=>_profile==null?_Login():_Profile();
Widget _Login()=>Scaffold(body:CustomScrollView(slivers:[SliverToBoxAdapter(child:_ProfileHeader(title:'حساب الطالب',subtitle:'مساحتك الأكاديمية في TRINEX',icon:Icons.person_rounded)),SliverPadding(padding:const EdgeInsets.fromLTRB(16,18,16,120),sliver:SliverToBoxAdapter(child:Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(24),border:Border.all(color:Theme.of(context).colorScheme.outline.withValues(alpha:.52))),child:Column(children:[Container(width:72,height:72,decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.12),shape:BoxShape.circle),child:const Icon(Icons.school_rounded,color:AppColors.primary,size:35)),const SizedBox(height:15),const Text('ابدأ رحلتك الدراسية',style:TextStyle(fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('سجّل الدخول للوصول إلى تخصصك، المواد، الجدول وXP.',textAlign:TextAlign.center),const SizedBox(height:22),TextField(controller:_id,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الرقم الجامعي',prefixIcon:Icon(Icons.badge_outlined))),const SizedBox(height:12),TextField(controller:_password,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور / رمز التحقق',prefixIcon:Icon(Icons.lock_outline))),if(_error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(_error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:_loading?null:_login,icon:const Icon(Icons.login_rounded),label:const Text('تسجيل الدخول'))),const SizedBox(height:6),TextButton(onPressed:()=>context.pop(),child:const Text('العودة كزائر'))]))))]));
Widget _Profile()=>Scaffold(body:CustomScrollView(slivers:[SliverToBoxAdapter(child:_ProfileHeader(title:'ملفي الدراسي',subtitle:'بياناتك وتقدمك في مكان واحد',icon:Icons.person_rounded,action:IconButton(onPressed:_logout,icon:const Icon(Icons.logout_rounded,color:Colors.white)))),SliverPadding(padding:const EdgeInsets.fromLTRB(16,18,16,120),sliver:SliverList(delegate:SliverChildListDelegate([_Identity(),const SizedBox(height:12),_Stats(),const SizedBox(height:20),const Text('لوحتك الدراسية',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),_Link(icon:Icons.menu_book_rounded,title:'المواد الدراسية',subtitle:'مواد تخصصك والفصل الحالي',route:'/materials'),_Link(icon:Icons.calendar_month_rounded,title:'الجدول الدراسي',subtitle:'حصصك الأسبوعية ومواعيدك',route:'/schedule'),_Link(icon:Icons.insights_rounded,title:'التقدم الدراسي',subtitle:'تقدمك وملفاتك المقروءة',route:'/progress'),_Link(icon:Icons.bolt_rounded,title:'XP والمستوى',subtitle:'نقاطك ومستواك الحالي',route:'/xp'),_Link(icon:Icons.emoji_events_rounded,title:'الشارات',subtitle:'إنجازاتك الدراسية',route:'/badges')])))]));
Widget _Identity(){final p=_profile!;return Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:AppColors.navy,borderRadius:BorderRadius.circular(24)),child:Row(children:[Container(width:64,height:64,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.10),shape:BoxShape.circle),child:const Icon(Icons.person_rounded,color:AppColors.primary,size:32)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name.isEmpty?'طالب':p.name,style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('الرقم الجامعي: ${p.number}',style:const TextStyle(color:Colors.white70,fontSize:12)),if(p.departmentName!=null)Text(p.departmentName!,style:const TextStyle(color:Colors.white70,fontSize:12))]))]));}
Widget _Stats(){final xp=_stats['xp_total']??_stats['xpTotal']??0;final level=_stats['level']??1;return Row(children:[Expanded(child:_Stat(value:'$level',label:'المستوى',icon:Icons.trending_up_rounded)),const SizedBox(width:10),Expanded(child:_Stat(value:'$xp',label:'XP',icon:Icons.bolt_rounded))]);}
}
class _ProfileHeader extends StatelessWidget{const _ProfileHeader({required this.title,required this.subtitle,required this.icon,this.action});final String title,subtitle;final IconData icon;final Widget? action;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.fromLTRB(18,10,18,22),decoration:const BoxDecoration(gradient:LinearGradient(begin:AlignmentDirectional.topStart,end:AlignmentDirectional.bottomEnd,colors:[AppColors.navy,Color(0xFF173D5A)]),borderRadius:BorderRadius.vertical(bottom:Radius.circular(28))),child:SafeArea(bottom:false,child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.1),borderRadius:BorderRadius.circular(15)),child:Icon(icon,color:AppColors.primary)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(subtitle,style:const TextStyle(color:Colors.white70,fontSize:12))])),if(action!=null)action!])));}
class _Stat extends StatelessWidget{const _Stat({required this.value,required this.label,required this.icon});final String value,label;final IconData icon;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(19),border:Border.all(color:Theme.of(context).colorScheme.outline.withValues(alpha:.5))),child:Column(children:[Icon(icon,color:AppColors.primary),const SizedBox(height:6),Text(value,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900)),Text(label,style:Theme.of(context).textTheme.bodySmall)]));}
class _Link extends StatelessWidget{const _Link({required this.icon,required this.title,required this.subtitle,required this.route});final IconData icon;final String title,subtitle,route;@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:9),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(19),border:Border.all(color:Theme.of(context).colorScheme.outline.withValues(alpha:.5))),child:ListTile(onTap:()=>context.go(route),contentPadding:const EdgeInsets.symmetric(horizontal:13,vertical:3),leading:Container(width:42,height:42,decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.11),borderRadius:BorderRadius.circular(13)),child:Icon(icon,color:AppColors.primary)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(subtitle),trailing:const Icon(Icons.chevron_left_rounded)));}
