import 'package:flutter/material.dart';
import '../../core/theme/design_tokens.dart';
import '../../data/mock_data.dart';

class StudentScreen extends StatelessWidget {
  const StudentScreen({super.key});
  @override Widget build(BuildContext context) {
    final s = MockData.student;
    return ListView(padding: const EdgeInsets.fromLTRB(36, 30, 36, 120), children: [
      Container(padding: const EdgeInsets.fromLTRB(34, 30, 34, 26), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(30), border: Border.all(color: AppColors.border)), child: Column(children: [
        Container(width: 156, height: 156, padding: const EdgeInsets.all(5), decoration: BoxDecoration(shape: BoxShape.circle, gradient: const LinearGradient(colors: [AppColors.cyan, AppColors.purple]), boxShadow: [BoxShadow(color: AppColors.cyan.withValues(alpha: .2), blurRadius: 28)]), child: ClipOval(child: Image.asset('assets/images/mock_student_avatar.jpg', fit: BoxFit.cover))),
        const SizedBox(height: 22), Text(s.name, style: const TextStyle(fontSize: 32, fontWeight: FontWeight.w900)), const SizedBox(height: 6), Text(s.major, style: const TextStyle(color: AppColors.cyan, fontSize: 19, fontWeight: FontWeight.w800)), const SizedBox(height: 14), _Pill(text: s.number), const SizedBox(height: 18), Wrap(alignment: WrapAlignment.center, spacing: 20, runSpacing: 10, children: [Text('المشرف: ${s.supervisor}', style: const TextStyle(color: AppColors.muted)), Text(s.email, style: const TextStyle(color: AppColors.muted)), const Text('•'), const Text('الحالة: طالب منتظم', style: TextStyle(color: AppColors.success, fontWeight: FontWeight.w800))])
      ])),
      const SizedBox(height: 18),
      _StatCard(title: 'المعدل التراكمي (GPA)', value: s.gpa.toStringAsFixed(2), suffix: '/ ${s.maxGpa.toStringAsFixed(2)}', note: 'مرتبة شرف أولى (ممتاز مرتفع)', color: AppColors.success),
      const SizedBox(height: 16),
      _StatCard(title: 'الفصل الدراسي', value: '${s.semester}', suffix: '/ ${s.totalSemesters} فصول', note: 'المستوى الأكاديمي الثالث', color: AppColors.cyan),
      const SizedBox(height: 16),
      _HoursCard(earned: s.earnedHours, required: s.requiredHours),
      const SizedBox(height: 18),
      Row(children: [Expanded(child: _ActionCard('مقررات الفصل', Icons.menu_book_rounded, AppColors.cyan)), const SizedBox(width: 12), Expanded(child: _ActionCard('جدول المحاضرات', Icons.calendar_month_rounded, const Color(0xFF4E7BFF))), const SizedBox(width: 12), Expanded(child: _ActionCard('الشارات ونقاط XP', Icons.workspace_premium_rounded, AppColors.gold))]),
      const SizedBox(height: 20),
      Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: AppColors.border)), child: Row(children: [Expanded(child: FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.logout_rounded), label: const Text('تسجيل الخروج'), style: FilledButton.styleFrom(backgroundColor: const Color(0xFF5C1530), foregroundColor: const Color(0xFFFF8BA9), minimumSize: const Size.fromHeight(54)))), const SizedBox(width: 12), Expanded(child: OutlinedButton.icon(onPressed: () {}, icon: const Icon(Icons.edit_outlined), label: const Text('تعديل الملف'), style: OutlinedButton.styleFrom(minimumSize: const Size.fromHeight(54))))])),
    ]);
  }
}
class _Pill extends StatelessWidget { const _Pill({required this.text}); final String text; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 9), decoration: BoxDecoration(color: AppColors.elevated, borderRadius: BorderRadius.circular(22), border: Border.all(color: AppColors.border)), child: Text(text, style: const TextStyle(color: AppColors.muted, fontSize: 17, fontWeight: FontWeight.w700))); }
class _StatCard extends StatelessWidget { const _StatCard({required this.title, required this.value, required this.suffix, required this.note, required this.color}); final String title, value, suffix, note; final Color color; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(28), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(28), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text(title, style: const TextStyle(color: AppColors.muted, fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 8), RichText(text: TextSpan(children: [TextSpan(text: value, style: const TextStyle(color: Colors.white, fontSize: 48, fontWeight: FontWeight.w900)), TextSpan(text: '  $suffix', style: const TextStyle(color: AppColors.muted, fontSize: 18))])), const SizedBox(height: 7), Text(note, style: TextStyle(color: color, fontSize: 17, fontWeight: FontWeight.w800))])); }
class _HoursCard extends StatelessWidget { const _HoursCard({required this.earned, required this.required}); final int earned, required; @override Widget build(BuildContext context) { final ratio = earned / required; return Container(padding: const EdgeInsets.all(28), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(28), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [const Text('الساعات المنجزة', style: TextStyle(color: AppColors.muted, fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 6), RichText(text: TextSpan(children: [TextSpan(text: '$earned', style: const TextStyle(color: Colors.white, fontSize: 48, fontWeight: FontWeight.w900)), TextSpan(text: '  / $required ساعة', style: const TextStyle(color: AppColors.muted, fontSize: 18))])), const SizedBox(height: 16), ClipRRect(borderRadius: BorderRadius.circular(12), child: LinearProgressIndicator(value: ratio, minHeight: 12, backgroundColor: AppColors.elevated, valueColor: const AlwaysStoppedAnimation(AppColors.cyan))) ])); } }
class _ActionCard extends StatelessWidget { const _ActionCard(this.title, this.icon, this.color); final String title; final IconData icon; final Color color; @override Widget build(BuildContext context) => Container(height: 112, padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: AppColors.border)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(icon, color: color, size: 30), const SizedBox(height: 8), Text(title, textAlign: TextAlign.center, style: const TextStyle(fontWeight: FontWeight.w800))])); }
