import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/constants/app_constants.dart';
import '../../core/localization/app_localizations.dart';
import '../../core/network/api_client.dart';
import '../../core/network/authenticated_client.dart';
import '../../core/storage/auth_storage.dart';
import '../../data/models/student_profile.dart';
import '../../data/repositories/student_repository.dart';
import '../../shared/widgets/app_card.dart';

class StudentScreen extends StatefulWidget{const StudentScreen({super.key});@override State<StudentScreen>createState()=>_StudentScreenState();}
class _StudentScreenState extends State<StudentScreen>{ApiClient? _client;late Future<_StudentData> _future;@override void initState(){super.initState();_future=_load();}Future<_StudentData>_load()async{_client??=await AuthenticatedClient.create();final r=StudentRepository(_client!);final p=await r.profile();final stats=await r.stats();return _StudentData(p,stats);}Future<void>_reload()async{setState(()=>_future=_load());await _future;}@override void dispose(){_client?.dispose();super.dispose();}
Future<void>_logout()async{final storage=await AuthStorage.create();final token=await storage.accessToken;if(token?.isNotEmpty==true){try{final c=await AuthenticatedClient.create();await c.postJson('/api/v1/auth/logout');c.dispose();}catch(_){}}await storage.clear();if(mounted)context.go('/login');}
@override Widget build(BuildContext context){return RefreshIndicator(onRefresh:_reload,child:FutureBuilder<_StudentData>(future:_future,builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text(s.error is ApiException?(s.error as ApiException).message:AppLocalizations.of(context).t('connectionFailed')));final p=s.data!.profile;final stats=s.data!.stats;return ListView(padding:const EdgeInsetsDirectional.fromSTEB(14.72,12,14.72,92),children:[AppCard(padding:const EdgeInsets.all(16),child:Column(children:[Container(width:88,height:88,decoration:BoxDecoration(shape:BoxShape.circle,gradient:LinearGradient(colors:[context.colors.secondary,context.colors.primary])),child:const Icon(Icons.person_rounded,color:Colors.white,size:48)),const SizedBox(height:10),Text(p.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(p.departmentName??'',style:TextStyle(color:context.colors.primary,fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(height:7),_Pill(p.number),const SizedBox(height:12),Text(p.semesterName??'الفصل غير محدد',style:TextStyle(color:context.colors.onSurfaceVariant,fontSize:10.5))])),const SizedBox(height:10),AppCard(child:Row(children:[Expanded(child:_Stat('المستوى','${stats['level']??1}')),const SizedBox(width:8),Expanded(child:_Stat('XP','${stats['xp_total']??0}')),const SizedBox(width:8),Expanded(child:_Stat('الفصل',p.semesterName??'—'))])),const SizedBox(height:10),Row(children:[Expanded(child:_Action('المواد',Icons.menu_book_rounded,()=>context.go('/materials'))),const SizedBox(width:8),Expanded(child:_Action('الجدول',Icons.calendar_month_rounded,()=>context.go('/schedule'))),const SizedBox(width:8),Expanded(child:_Action('الشارات',Icons.workspace_premium_rounded,()=>context.go('/badges')))]),const SizedBox(height:10),FilledButton.icon(onPressed:_logout,icon:const Icon(Icons.logout_rounded,size:16),label:const Text('تسجيل الخروج'))]);}));}
}
class _StudentData{const _StudentData(this.profile,this.stats);final StudentProfile profile;final Map<String,dynamic>stats;}
class _Pill extends StatelessWidget{const _Pill(this.text);final String text;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:5),decoration:BoxDecoration(color:c.colors.surfaceContainerHigh,borderRadius:BorderRadius.circular(14),border:Border.all(color:c.colors.outline)),child:Text(text,style:TextStyle(fontSize:10,color:c.colors.onSurfaceVariant,fontWeight:FontWeight.w700)));}
class _Stat extends StatelessWidget{const _Stat(this.label,this.value);final String label,value;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:BoxDecoration(color:c.colors.surfaceContainerHigh,borderRadius:BorderRadius.circular(12)),child:Column(children:[Text(value,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:c.colors.primary,fontWeight:FontWeight.w900,fontSize:13)),const SizedBox(height:2),Text(label,style:TextStyle(fontSize:9,color:c.colors.onSurfaceVariant))]));}
class _Action extends StatelessWidget{const _Action(this.label,this.icon,this.onTap);final String label;final IconData icon;final VoidCallback onTap;@override Widget build(BuildContext c)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(13),child:Container(height:62,decoration:BoxDecoration(color:c.colors.surface,borderRadius:BorderRadius.circular(13),border:Border.all(color:c.colors.outline)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:21,color:c.colors.primary),const SizedBox(height:4),Text(label,style:const TextStyle(fontSize:9.5,fontWeight:FontWeight.w800))])));}
