import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/theme/design_tokens.dart';
import '../../data/mock_data.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});
  @override Widget build(BuildContext context) {
    final s = MockData.student;
    return ListView(padding: const EdgeInsets.fromLTRB(36, 30, 36, 120), children: [
      Container(padding: const EdgeInsets.all(28), decoration: BoxDecoration(gradient: LinearGradient(colors: [Theme.of(context).colorScheme.primary.withValues(alpha: .26), AppColors.surface]), borderRadius: BorderRadius.circular(30), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text('مرحباً ${s.name.split(' ').first} 👋', style: const TextStyle(fontSize: 30, fontWeight: FontWeight.w900)), const SizedBox(height: 8), const Text('كل ما تحتاجه لحياتك الأكاديمية في TRINEX', style: TextStyle(color: AppColors.muted, fontSize: 17)), const SizedBox(height: 22), Row(children: [Expanded(child: _QuickStat('GPA', s.gpa.toStringAsFixed(2), AppColors.success)), const SizedBox(width: 12), Expanded(child: _QuickStat('المستوى', '${s.level}', AppColors.gold)), const SizedBox(width: 12), Expanded(child: _QuickStat('XP', '${s.xp}', AppColors.cyan))])])),
      const SizedBox(height: 24),
      const Text('الوصول السريع', textAlign: TextAlign.right, style: TextStyle(fontSize: 24, fontWeight: FontWeight.w900)), const SizedBox(height: 14),
      Row(children: [Expanded(child: _Tile('المواد', Icons.menu_book_rounded, AppColors.cyan, () => context.go('/materials'))), const SizedBox(width: 12), Expanded(child: _Tile('الجداول', Icons.calendar_month_rounded, const Color(0xFF8B6CFF), () => context.go('/schedule'))), const SizedBox(width: 12), Expanded(child: _Tile('نظام XP', Icons.workspace_premium_rounded, AppColors.gold, () => context.go('/system')))]),
      const SizedBox(height: 26),
      Row(mainAxisAlignment: MainAxisAlignment.end, children: [const Text('أحدث الأخبار', style: TextStyle(fontSize: 24, fontWeight: FontWeight.w900)), const SizedBox(width: 10), const Icon(Icons.article_outlined, color: AppColors.cyan)]), const SizedBox(height: 14),
      for (final item in MockData.news.take(2)) Padding(padding: const EdgeInsets.only(bottom: 14), child: Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: AppColors.border)), child: Row(children: [Container(width: 54, height: 54, decoration: BoxDecoration(color: AppColors.cyan.withValues(alpha: .12), borderRadius: BorderRadius.circular(16)), child: const Icon(Icons.campaign_rounded, color: AppColors.cyan)), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Text(item.title, textAlign: TextAlign.right, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16)), const SizedBox(height: 5), Text(item.date, style: const TextStyle(color: AppColors.muted))]))]))),
    ]);
  }
}
class _QuickStat extends StatelessWidget { const _QuickStat(this.label, this.value, this.color); final String label, value; final Color color; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.symmetric(vertical: 16), decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(20), border: Border.all(color: AppColors.border)), child: Column(children: [Text(value, style: TextStyle(color: color, fontSize: 25, fontWeight: FontWeight.w900)), const SizedBox(height: 3), Text(label, style: const TextStyle(color: AppColors.muted))])); }
class _Tile extends StatelessWidget { const _Tile(this.title, this.icon, this.color, this.onTap); final String title; final IconData icon; final Color color; final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(24), child: Container(height: 120, decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: AppColors.border)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(icon, color: color, size: 33), const SizedBox(height: 10), Text(title, style: const TextStyle(fontWeight: FontWeight.w800))]))); }
